CREATE CACHED TABLE IF NOT EXISTS "PUBLIC"."PLUGIN_MARKET_ENTRY" (
    "ID" CHARACTER VARYING(128) NOT NULL,
    "VERSION" CHARACTER VARYING(64) NOT NULL,
    "SOURCE" CHARACTER LARGE OBJECT,
    "MANIFEST" CHARACTER LARGE OBJECT NOT NULL,
    "SIGNATURE" CHARACTER LARGE OBJECT,
    "PUBLISHER_KEY" CHARACTER LARGE OBJECT,
    "PERMISSIONS_JSON" CHARACTER LARGE OBJECT NOT NULL,
    "CHECKSUM" CHARACTER VARYING(128),
    "UPDATE_POLICY" CHARACTER VARYING(32) NOT NULL,
    "PUBLISHED_AT" TIMESTAMP NOT NULL,
    "ENABLED" BOOLEAN NOT NULL,
    CONSTRAINT "PK_PLUGIN_MARKET_ENTRY" PRIMARY KEY ("ID", "VERSION")
);
CREATE INDEX IF NOT EXISTS "IDX_PLUGIN_MARKET_ID" ON "PUBLIC"."PLUGIN_MARKET_ENTRY"("ID");
