# 内置配置
# https://mybatis-flex.com/zh/base/configuration.html
mybatis-flex:
  mapper-locations: classpath*:/mapper/**/*.xml
  # 启动时是否检查 MyBatis XML 文件的存在，默认不检查
  check-config-location: false
  global-config:
    key-config:
      keyType: Auto
    # 是否打印 Logo banner
    print-banner: true
    version-column: version
    tenant-column: tenant_id
    logic-delete-column: delFlag
    # 逻辑已删除值(可按需求随意修改)
    deleted-value-of-logic-delete: 1
    # 逻辑未删除值
    normal-value-of-logic-delete: 0
