-- 扩展模式：iam
INSERT INTO "PUBLIC"."AUTH_MENU" ("ID","NAME","CODE","TYPE","PARENT_ID","TENANT_ID","PATH","REDIRECT","ICON","COMPONENT","DESCRIPTION","SHOW","STATUS","ORDER","DEL_FLAG","CREATE_BY","CREATE_TIME","UPDATE_BY","UPDATE_TIME") VALUES
(2050,'教育中心','EducationCenter','CATALOG',NULL,1,'/education-center','/education-center/learning','lucide:graduation-cap','','学习、练习、复习与 AI 辅学',TRUE,1,6,0,'system',CURRENT_TIMESTAMP,'system',CURRENT_TIMESTAMP),
(2051,'学习','EducationLearning','MENU',2050,1,'/education-center/learning',NULL,'lucide:book-open','feature:education.learning','课程与学习资源',TRUE,1,1,0,'system',CURRENT_TIMESTAMP,'system',CURRENT_TIMESTAMP),
(2052,'练习','EducationPractice','MENU',2050,1,'/education-center/practice',NULL,'lucide:clipboard-check','feature:education.practice','题库、错题与考试',TRUE,1,2,0,'system',CURRENT_TIMESTAMP,'system',CURRENT_TIMESTAMP),
(2053,'AI 辅学','EducationTutor','MENU',2050,1,'/education-center/ai-tutor',NULL,'lucide:sparkles','feature:education.tutor','讲解、出题、规划与报告',TRUE,1,3,0,'system',CURRENT_TIMESTAMP,'system',CURRENT_TIMESTAMP),
(2054,'学习分析','EducationAnalytics','MENU',2050,1,'/education-center/analytics',NULL,'lucide:chart-no-axes-combined','feature:education.analytics','学习报告与趋势',TRUE,1,4,0,'system',CURRENT_TIMESTAMP,'system',CURRENT_TIMESTAMP);

INSERT INTO "PUBLIC"."AUTH_ROLE_SCOPE_MENU" ("ROLE_ID","MENU_ID","TENANT_ID","STATUS","DEL_FLAG","CREATE_BY","CREATE_TIME","UPDATE_BY","UPDATE_TIME")
SELECT R."ID", M."ID", 1, 1, 0, 'system', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP
FROM "PUBLIC"."AUTH_ROLE" R CROSS JOIN "PUBLIC"."AUTH_MENU" M
WHERE R."ID" IN (1,2,3) AND M."ID" BETWEEN 2050 AND 2054;

INSERT INTO "PUBLIC"."AUTH_TENANT_MENU" ("TENANT_ID","MENU_ID","STATUS","CREATE_TIME","UPDATE_TIME")
SELECT 1, M."ID", 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
FROM "PUBLIC"."AUTH_MENU" M WHERE M."ID" BETWEEN 2050 AND 2054;

INSERT INTO "PUBLIC"."AUTH_ROLE_SCOPE_AUTH_CODE" ("ROLE_ID","AUTH_CODE_ID","TENANT_ID","STATUS","DEL_FLAG","CREATE_BY","CREATE_TIME","UPDATE_BY","UPDATE_TIME")
SELECT R."ID", C."ID", 1, 1, 0, 'system', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP
FROM "PUBLIC"."AUTH_ROLE" R CROSS JOIN "PUBLIC"."AUTH_AUTH_CODE" C
WHERE R."ID" IN (1,2) AND C."ID" IN (53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,211,212,213);

INSERT INTO "PUBLIC"."AUTH_TENANT_AUTH_CODE" ("TENANT_ID","AUTH_CODE_ID","STATUS","CREATE_TIME","UPDATE_TIME")
SELECT 1, C."ID", 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
FROM "PUBLIC"."AUTH_AUTH_CODE" C
WHERE C."ID" IN (53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,211,212,213);
