INSERT INTO "PUBLIC"."EDU_REVIEW_TASK"
    ("ID", "STUDENT_ID", "KNOWLEDGE_ID", "REVIEW_DATE", "REVIEW_ROUND", "STATUS", "RESULT_SCORE", "COMPLETED_AT", "TENANT_ID", "CREATE_BY", "UPDATE_BY", "DEL_FLAG")
VALUES (1, 1, 1001, DATE '2026-09-10', 1, 0, NULL, NULL, 1, 'system', 'system', 0);

INSERT INTO "PUBLIC"."EDU_STUDY_PLAN"
    ("ID", "STUDENT_ID", "TARGET_KNOWLEDGE_ID", "NAME", "START_DATE", "END_DATE", "STATUS", "TENANT_ID", "CREATE_BY", "UPDATE_BY", "DEL_FLAG")
VALUES (1, 1, 1001, '一元一次方程巩固计划', DATE '2026-09-08', DATE '2026-09-14', 0, 1, 'system', 'system', 0);

INSERT INTO "PUBLIC"."EDU_STUDY_PLAN_ITEM"
    ("ID", "PLAN_ID", "KNOWLEDGE_ID", "PLAN_DATE", "ORDER_NO", "STATUS", "COMPLETED_AT", "TENANT_ID", "CREATE_BY", "UPDATE_BY", "DEL_FLAG")
VALUES (1, 1, 1001, DATE '2026-09-09', 1, 2, TIMESTAMP '2026-09-09 19:30:00', 1, 'system', 'system', 0);

INSERT INTO "PUBLIC"."EDU_WRONG_QUESTION"
    ("ID", "STUDENT_ID", "QUESTION_ID", "KNOWLEDGE_ID", "STUDENT_ANSWER", "CORRECT_TIMES", "CREATED_AT", "TENANT_ID", "STATUS", "DEL_FLAG", "CREATE_BY", "UPDATE_BY")
VALUES (1, 1, 1, 1001, 'C', 0, TIMESTAMP '2026-09-08 18:20:00', 1, 1, 0, 'system', 'system');

INSERT INTO "PUBLIC"."EDU_LEARNING_STATE"
    ("ID", "STUDENT_ID", "KNOWLEDGE_ID", "STATE", "TENANT_ID", "STATUS", "DEL_FLAG", "CREATE_BY", "UPDATE_BY")
VALUES (1, 1, 1001, 'PROFICIENT', 1, 1, 0, 'system', 'system');

INSERT INTO "PUBLIC"."EDU_ACHIEVEMENT"
    ("ID", "STUDENT_ID", "CODE", "NAME", "DESCRIPTION", "ICON", "EARNED_AT", "TENANT_ID", "STATUS", "DEL_FLAG", "CREATE_BY", "UPDATE_BY")
VALUES (1, 1, 'ALGEBRA_FOUNDATION', '代数基础达标', '完成一元一次方程阶段测验并达到 90 分以上。', 'achievement-algebra', TIMESTAMP '2026-09-08 20:00:00', 1, 1, 0, 'system', 'system');
