package com.shiyu.ai.agent.contract.runtime;

/**
 * 定义 AI 运行 事件 Type 可用的枚举值及其业务语义。
 */
public enum AiRunEventType {
    RUN_STARTED,
    TURN_STARTED,
    TURN_COMPLETED,
    STEP_STARTED,
    STEP_COMPLETED,
    PROMPT_ASSEMBLED,
    RETRIEVAL_STARTED,
    RETRIEVAL_COMPLETED,
    MODEL_STARTED,
    MODEL_BLOCK_STARTED,
    MODEL_DELTA,
    MODEL_REASONING_DELTA,
    MODEL_TOOL_CALL_DELTA,
    MODEL_BLOCK_COMPLETED,
    TOOL_REQUESTED,
    TOOL_APPROVAL_REQUIRED,
    TOOL_APPROVAL_DECIDED,
    TOOL_COMPLETED,
    MEMORY_READ,
    MEMORY_WRITE,
    MODEL_USAGE,
    MODEL_COMPLETED,
    RUN_COMPLETED,
    RUN_FAILED,
    RUN_CANCELLED
}
