CREATE CACHED TABLE IF NOT EXISTS "PUBLIC"."AI_APP" (
    "ID" CHARACTER VARYING(64) NOT NULL,
    "TENANT_ID" BIGINT NOT NULL,
    "OWNER_USER_ID" BIGINT NOT NULL,
    "NAME" CHARACTER VARYING(255) NOT NULL,
    "DESCRIPTION" CHARACTER LARGE OBJECT,
    "STATUS" CHARACTER VARYING(24) NOT NULL,
    "PUBLISHED_VERSION_ID" CHARACTER VARYING(64),
    "CREATED_AT" TIMESTAMP NOT NULL,
    "UPDATED_AT" TIMESTAMP NOT NULL,
    CONSTRAINT "PK_AI_APP" PRIMARY KEY ("ID")
);
CREATE INDEX IF NOT EXISTS "IDX_AI_APP_OWNER" ON "PUBLIC"."AI_APP"("TENANT_ID", "OWNER_USER_ID", "STATUS");

CREATE CACHED TABLE IF NOT EXISTS "PUBLIC"."AI_APP_VERSION" (
    "ID" CHARACTER VARYING(64) NOT NULL,
    "APP_ID" CHARACTER VARYING(64) NOT NULL,
    "TENANT_ID" BIGINT NOT NULL,
    "VERSION" CHARACTER VARYING(64) NOT NULL,
    "CONFIG_JSON" CHARACTER LARGE OBJECT NOT NULL,
    "STATUS" CHARACTER VARYING(24) NOT NULL,
    "CREATED_AT" TIMESTAMP NOT NULL,
    "PUBLISHED_AT" TIMESTAMP,
    CONSTRAINT "PK_AI_APP_VERSION" PRIMARY KEY ("ID"),
    CONSTRAINT "UK_AI_APP_VERSION" UNIQUE ("APP_ID", "VERSION")
);
CREATE INDEX IF NOT EXISTS "IDX_AI_APP_VERSION_APP" ON "PUBLIC"."AI_APP_VERSION"("TENANT_ID", "APP_ID", "STATUS");

CREATE CACHED TABLE IF NOT EXISTS "PUBLIC"."AI_RUN" (
    "ID" CHARACTER VARYING(64) NOT NULL,
    "TENANT_ID" BIGINT NOT NULL,
    "OWNER_USER_ID" BIGINT NOT NULL,
    "APP_ID" CHARACTER VARYING(64),
    "APP_VERSION_ID" CHARACTER VARYING(64),
    "SOURCE_TYPE" CHARACTER VARYING(32) NOT NULL,
    "SOURCE_ID" CHARACTER VARYING(128) NOT NULL,
    "PARENT_RUN_ID" CHARACTER VARYING(64),
    "TRACE_ID" CHARACTER VARYING(128) NOT NULL,
    "CONVERSATION_ID" CHARACTER VARYING(64),
    "GENERATION_ID" CHARACTER VARYING(64),
    "EXECUTION_ID" CHARACTER VARYING(64),
    "MODEL" CHARACTER VARYING(128),
    "PROMPT_HASH" CHARACTER VARYING(128),
    "STATUS" CHARACTER VARYING(24) NOT NULL,
    "PROMPT_TOKENS" BIGINT NOT NULL DEFAULT 0,
    "COMPLETION_TOKENS" BIGINT NOT NULL DEFAULT 0,
    "ESTIMATED_USAGE" BOOLEAN NOT NULL DEFAULT TRUE,
    "COST_SNAPSHOT" CHARACTER LARGE OBJECT,
    "CREATED_AT" TIMESTAMP NOT NULL,
    "COMPLETED_AT" TIMESTAMP,
    "ERROR_CODE" CHARACTER VARYING(128),
    "LAST_EVENT_SEQ" BIGINT NOT NULL DEFAULT 0,
    "VERSION" BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT "PK_AI_RUN" PRIMARY KEY ("ID")
);
CREATE INDEX IF NOT EXISTS "IDX_AI_RUN_OWNER" ON "PUBLIC"."AI_RUN"("TENANT_ID", "OWNER_USER_ID", "CREATED_AT");
CREATE INDEX IF NOT EXISTS "IDX_AI_RUN_TRACE" ON "PUBLIC"."AI_RUN"("TENANT_ID", "TRACE_ID");

CREATE CACHED TABLE IF NOT EXISTS "PUBLIC"."AI_RUN_EVENT" (
    "RUN_ID" CHARACTER VARYING(64) NOT NULL,
    "TENANT_ID" BIGINT NOT NULL,
    "SEQ" BIGINT NOT NULL,
    "TYPE" CHARACTER VARYING(48) NOT NULL,
    "SCHEMA_VERSION" INTEGER NOT NULL DEFAULT 1,
    "TURN_ID" CHARACTER VARYING(64),
    "STEP_ID" CHARACTER VARYING(64),
    "PARENT_EVENT_SEQ" BIGINT,
    "CONVERSATION_ID" CHARACTER VARYING(64),
    "GENERATION_ID" CHARACTER VARYING(64),
    "EXECUTION_ID" CHARACTER VARYING(64),
    "APP_ID" CHARACTER VARYING(64),
    "APP_VERSION_ID" CHARACTER VARYING(64),
    "PROVIDER_REQUEST_ID" CHARACTER VARYING(255),
    "TRACE_ID" CHARACTER VARYING(128),
    "PAYLOAD" CHARACTER LARGE OBJECT NOT NULL,
    "REDACTED" BOOLEAN NOT NULL DEFAULT TRUE,
    "CREATED_AT" TIMESTAMP NOT NULL,
    CONSTRAINT "PK_AI_RUN_EVENT" PRIMARY KEY ("RUN_ID", "SEQ")
);
CREATE CACHED TABLE IF NOT EXISTS "PUBLIC"."AI_TOOL_APPROVAL" (
    "ID" CHARACTER VARYING(64) NOT NULL,
    "RUN_ID" CHARACTER VARYING(64) NOT NULL,
    "TENANT_ID" BIGINT NOT NULL,
    "OWNER_USER_ID" BIGINT NOT NULL,
    "TOOL_NAME" CHARACTER VARYING(255) NOT NULL,
    "ARGUMENTS_REDACTED" CHARACTER LARGE OBJECT,
    "STATUS" CHARACTER VARYING(24) NOT NULL,
    "CREATED_AT" TIMESTAMP NOT NULL,
    "DECIDED_AT" TIMESTAMP,
    "EXPIRES_AT" TIMESTAMP,
    CONSTRAINT "PK_AI_TOOL_APPROVAL" PRIMARY KEY ("ID")
);
CREATE INDEX IF NOT EXISTS "IDX_AI_TOOL_APPROVAL_RUN" ON "PUBLIC"."AI_TOOL_APPROVAL"("TENANT_ID", "RUN_ID", "STATUS");
