-- Platform conversation source of truth. Messages are never duplicated into memory tables.
CREATE CACHED TABLE IF NOT EXISTS "PUBLIC"."CHAT_CONVERSATION" (
    "ID" CHARACTER VARYING(64) NOT NULL,
    "TENANT_ID" BIGINT NOT NULL,
    "OWNER_USER_ID" BIGINT NOT NULL,
    "SCENE_TYPE" CHARACTER VARYING(64) NOT NULL,
    "TITLE" CHARACTER VARYING(255),
    "STATUS" CHARACTER VARYING(16) NOT NULL,
    "PARENT_CONVERSATION_ID" CHARACTER VARYING(64),
    "BRANCH_FROM_MESSAGE_ID" CHARACTER VARYING(64),
    "ACTIVE_LEAF_MESSAGE_ID" CHARACTER VARYING(64),
    "ROLLING_SUMMARY" CHARACTER LARGE OBJECT,
    "PLATFORM" CHARACTER VARYING(64),
    "MODEL" CHARACTER VARYING(128),
    "VERSION" BIGINT NOT NULL DEFAULT 0,
    "CREATED_AT" TIMESTAMP NOT NULL,
    "UPDATED_AT" TIMESTAMP NOT NULL,
    CONSTRAINT "PK_CHAT_CONVERSATION" PRIMARY KEY ("ID")
);
CREATE INDEX IF NOT EXISTS "IDX_CHAT_CONV_OWNER" ON "PUBLIC"."CHAT_CONVERSATION"("TENANT_ID", "OWNER_USER_ID", "STATUS");

CREATE CACHED TABLE IF NOT EXISTS "PUBLIC"."CHAT_MESSAGE" (
    "ID" CHARACTER VARYING(64) NOT NULL,
    "TENANT_ID" BIGINT NOT NULL,
    "CONVERSATION_ID" CHARACTER VARYING(64) NOT NULL,
    "PARENT_MESSAGE_ID" CHARACTER VARYING(64),
    "SOURCE_MESSAGE_ID" CHARACTER VARYING(64),
    "ROLE" CHARACTER VARYING(16) NOT NULL,
    "CONTENT" CHARACTER LARGE OBJECT NOT NULL,
    "CONTENT_PARTS" CHARACTER LARGE OBJECT,
    "TOOL_CALL" CHARACTER LARGE OBJECT,
    "STATUS" CHARACTER VARYING(16) NOT NULL,
    "SEQUENCE" INTEGER NOT NULL,
    "GENERATION_ID" CHARACTER VARYING(64),
    "CREATED_AT" TIMESTAMP NOT NULL,
    "UPDATED_AT" TIMESTAMP NOT NULL,
    CONSTRAINT "PK_CHAT_MESSAGE" PRIMARY KEY ("ID")
);
CREATE INDEX IF NOT EXISTS "IDX_CHAT_MESSAGE_CONV_SEQ" ON "PUBLIC"."CHAT_MESSAGE"("TENANT_ID", "CONVERSATION_ID", "SEQUENCE");

CREATE CACHED TABLE IF NOT EXISTS "PUBLIC"."CHAT_GENERATION_RUN" (
    "ID" CHARACTER VARYING(64) NOT NULL,
    "TENANT_ID" BIGINT NOT NULL,
    "CONVERSATION_ID" CHARACTER VARYING(64) NOT NULL,
    "INPUT_MESSAGE_ID" CHARACTER VARYING(64),
    "ASSISTANT_MESSAGE_ID" CHARACTER VARYING(64),
    "RUNTIME_RUN_ID" CHARACTER VARYING(64),
    "SPEAKER_ID" CHARACTER VARYING(128),
    "PLATFORM" CHARACTER VARYING(64),
    "MODEL" CHARACTER VARYING(128),
    "STATUS" CHARACTER VARYING(24) NOT NULL,
    "PROMPT_TOKENS" BIGINT DEFAULT 0,
    "COMPLETION_TOKENS" BIGINT DEFAULT 0,
    "LATENCY_MS" BIGINT DEFAULT 0,
    "ERROR_CODE" CHARACTER VARYING(128),
    "LAST_EVENT_SEQUENCE" INTEGER DEFAULT -1,
    "CANCEL_REQUESTED" BOOLEAN NOT NULL DEFAULT FALSE,
    "VERSION" BIGINT NOT NULL DEFAULT 0,
    "CREATED_AT" TIMESTAMP NOT NULL,
    "UPDATED_AT" TIMESTAMP NOT NULL,
    CONSTRAINT "PK_CHAT_GENERATION_RUN" PRIMARY KEY ("ID")
);
CREATE INDEX IF NOT EXISTS "IDX_CHAT_GENERATION_RUN_CONV" ON "PUBLIC"."CHAT_GENERATION_RUN"("TENANT_ID", "CONVERSATION_ID", "CREATED_AT");

-- Database-level admission reservation.  It closes the check-then-insert
-- race for retries on the same active user message; the row is released when
-- the GenerationRun reaches any terminal state.
CREATE CACHED TABLE IF NOT EXISTS "PUBLIC"."CHAT_GENERATION_ACTIVE" (
    "TENANT_ID" BIGINT NOT NULL,
    "CONVERSATION_ID" CHARACTER VARYING(64) NOT NULL,
    "INPUT_MESSAGE_ID" CHARACTER VARYING(64) NOT NULL,
    "GENERATION_ID" CHARACTER VARYING(64) NOT NULL,
    "CREATED_AT" TIMESTAMP NOT NULL,
    CONSTRAINT "PK_CHAT_GENERATION_ACTIVE" PRIMARY KEY ("TENANT_ID", "CONVERSATION_ID", "INPUT_MESSAGE_ID"),
    CONSTRAINT "UK_CHAT_GENERATION_ACTIVE_RUN" UNIQUE ("GENERATION_ID")
);

-- Generation events are a typed projection of AI_RUN_EVENT. Do not create a
-- second physical stream.

CREATE CACHED TABLE IF NOT EXISTS "PUBLIC"."CHAT_IDEMPOTENCY_KEY" (
    "TENANT_ID" BIGINT NOT NULL,
    "OWNER_USER_ID" BIGINT NOT NULL,
    "KEY_VALUE" CHARACTER VARYING(128) NOT NULL,
    "OPERATION" CHARACTER VARYING(64) NOT NULL,
    "RESOURCE_ID" CHARACTER VARYING(64) NOT NULL,
    "CREATED_AT" TIMESTAMP NOT NULL,
    CONSTRAINT "PK_CHAT_IDEMPOTENCY_KEY" PRIMARY KEY ("TENANT_ID", "OWNER_USER_ID", "KEY_VALUE", "OPERATION")
);

CREATE INDEX IF NOT EXISTS "IDX_CHAT_GENERATION_ACTIVE_TENANT" ON "PUBLIC"."CHAT_GENERATION_ACTIVE"("TENANT_ID");
CREATE INDEX IF NOT EXISTS "IDX_CHAT_IDEMPOTENCY_KEY_TENANT" ON "PUBLIC"."CHAT_IDEMPOTENCY_KEY"("TENANT_ID");

-- Conversation-owned product assets: characters, personas, lorebooks, prompts and group chats.
CREATE CACHED TABLE IF NOT EXISTS "PUBLIC"."CHAT_CHARACTER_ASSET" (
    "ID" CHARACTER VARYING(64) NOT NULL,
    "TENANT_ID" BIGINT NOT NULL,
    "OWNER_USER_ID" BIGINT NOT NULL,
    "CARD_JSON" CHARACTER LARGE OBJECT NOT NULL,
    "PNG_DATA" BLOB,
    "VISIBILITY" CHARACTER VARYING(16) NOT NULL,
    "CREATED_AT" TIMESTAMP NOT NULL,
    "UPDATED_AT" TIMESTAMP NOT NULL,
    CONSTRAINT "PK_CHAT_CHARACTER_ASSET" PRIMARY KEY ("ID")
);
CREATE INDEX IF NOT EXISTS "IDX_CHAT_CHARACTER_OWNER" ON "PUBLIC"."CHAT_CHARACTER_ASSET"("TENANT_ID", "OWNER_USER_ID");
CREATE CACHED TABLE IF NOT EXISTS "PUBLIC"."CHAT_PERSONA_ASSET" (
    "ID" CHARACTER VARYING(64) NOT NULL,
    "TENANT_ID" BIGINT NOT NULL,
    "OWNER_USER_ID" BIGINT NOT NULL,
    "PERSONA_JSON" CHARACTER LARGE OBJECT NOT NULL,
    "CREATED_AT" TIMESTAMP NOT NULL,
    "UPDATED_AT" TIMESTAMP NOT NULL,
    CONSTRAINT "PK_CHAT_PERSONA_ASSET" PRIMARY KEY ("ID")
);
CREATE INDEX IF NOT EXISTS "IDX_CHAT_PERSONA_OWNER" ON "PUBLIC"."CHAT_PERSONA_ASSET"("TENANT_ID", "OWNER_USER_ID");
CREATE CACHED TABLE IF NOT EXISTS "PUBLIC"."CHAT_LOREBOOK_ASSET" (
    "ID" CHARACTER VARYING(64) NOT NULL,
    "TENANT_ID" BIGINT NOT NULL,
    "OWNER_USER_ID" BIGINT NOT NULL,
    "ENTRY_JSON" CHARACTER LARGE OBJECT NOT NULL,
    "CREATED_AT" TIMESTAMP NOT NULL,
    "UPDATED_AT" TIMESTAMP NOT NULL,
    CONSTRAINT "PK_CHAT_LOREBOOK_ASSET" PRIMARY KEY ("ID")
);
CREATE INDEX IF NOT EXISTS "IDX_CHAT_LOREBOOK_OWNER" ON "PUBLIC"."CHAT_LOREBOOK_ASSET"("TENANT_ID", "OWNER_USER_ID");
CREATE CACHED TABLE IF NOT EXISTS "PUBLIC"."CHAT_PROMPT_TEMPLATE" (
    "ID" CHARACTER VARYING(64) NOT NULL,
    "TENANT_ID" BIGINT NOT NULL,
    "OWNER_USER_ID" BIGINT NOT NULL,
    "TEMPLATE_ID" CHARACTER VARYING(64) NOT NULL,
    "VERSION" INTEGER NOT NULL,
    "STATUS" CHARACTER VARYING(16) NOT NULL,
    "BODY" CHARACTER LARGE OBJECT NOT NULL,
    "VARIABLE_SCHEMA" CHARACTER LARGE OBJECT,
    "TEST_CASES" CHARACTER LARGE OBJECT,
    "CREATED_AT" TIMESTAMP NOT NULL,
    "PUBLISHED_AT" TIMESTAMP,
    CONSTRAINT "PK_CHAT_PROMPT_TEMPLATE" PRIMARY KEY ("ID"),
    CONSTRAINT "UK_CHAT_PROMPT_VERSION" UNIQUE ("TENANT_ID", "OWNER_USER_ID", "TEMPLATE_ID", "VERSION")
);
CREATE INDEX IF NOT EXISTS "IDX_CHAT_PROMPT_OWNER" ON "PUBLIC"."CHAT_PROMPT_TEMPLATE"("TENANT_ID", "OWNER_USER_ID", "TEMPLATE_ID");
CREATE CACHED TABLE IF NOT EXISTS "PUBLIC"."CHAT_GROUP_CHAT" (
    "ID" CHARACTER VARYING(64) NOT NULL,
    "TENANT_ID" BIGINT NOT NULL,
    "OWNER_USER_ID" BIGINT NOT NULL,
    "NAME" CHARACTER VARYING(255) NOT NULL,
    "PARTICIPANTS_JSON" CHARACTER LARGE OBJECT NOT NULL,
    "SPEAKER_POLICY" CHARACTER VARYING(32) NOT NULL,
    "MAX_TURNS" INTEGER NOT NULL,
    "TOKEN_BUDGET" INTEGER NOT NULL,
    "CREATED_AT" TIMESTAMP WITH TIME ZONE NOT NULL,
    "UPDATED_AT" TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT "PK_CHAT_GROUP_CHAT" PRIMARY KEY ("ID")
);
CREATE INDEX IF NOT EXISTS "IDX_CHAT_GROUP_OWNER" ON "PUBLIC"."CHAT_GROUP_CHAT"("TENANT_ID", "OWNER_USER_ID");
