package com.shiyu.ai.runtime;

public enum AiRunEventType {
    RUN_STARTED, PROMPT_ASSEMBLED, RETRIEVAL_STARTED, RETRIEVAL_COMPLETED,
    MODEL_STARTED, MODEL_DELTA, TOOL_REQUESTED, TOOL_APPROVAL_REQUIRED,
    TOOL_COMPLETED, MEMORY_READ, MEMORY_WRITE, MODEL_USAGE,
    RUN_COMPLETED, RUN_FAILED, RUN_CANCELLED
}
