-- PostgreSQL baseline generated from the validated H2 resources.
-- Do not edit generated sections; update the source baseline and regenerate.

-- Source: modules/applications/shiyu-application/src/main/resources/db/baseline/h2/schema/application/00_baseline.sql
-- Initializer metadata. This table is not part of the 76 application tables.

CREATE TABLE common_schema_baseline (
    id INTEGER NOT NULL,
    baseline_version CHARACTER VARYING(64) NOT NULL,
    seed_profile CHARACTER VARYING(64) NOT NULL,
    installed_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT pk_common_schema_baseline PRIMARY KEY (id),
    CONSTRAINT ck_common_schema_baseline_singleton CHECK (id = 1)
);

-- Source: modules/infrastructure/shiyu-common-storage/src/main/resources/db/baseline/h2/schema/storage/01_storage.sql
-- Final H2 schema baseline. Generated from the validated schema; do not add migrations here.

CREATE TABLE storage_object(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY  NOT NULL,
    tenant_id BIGINT NOT NULL,
    space_id BIGINT DEFAULT NULL,
    namespace CHARACTER VARYING(255) NOT NULL,
    object_key CHARACTER VARYING(1024) NOT NULL,
    storage_provider CHARACTER VARYING(32) DEFAULT 'local' NOT NULL,
    original_name CHARACTER VARYING(512) NOT NULL,
    content_type CHARACTER VARYING(128) DEFAULT 'application/octet-stream',
    file_size BIGINT DEFAULT 0 NOT NULL,
    checksum CHARACTER VARYING(64) DEFAULT NULL,
    status CHARACTER VARYING(20) DEFAULT 'PENDING' NOT NULL,
    metadata_json TEXT DEFAULT NULL,
    create_by CHARACTER VARYING(64) DEFAULT NULL,
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_by CHARACTER VARYING(64) DEFAULT NULL,
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP DEFAULT NULL,
    CONSTRAINT pk_storage_object PRIMARY KEY(id)
);

CREATE UNIQUE  INDEX uk_storage_object_tenant_key ON storage_object(tenant_id, object_key);

CREATE INDEX idx_storage_object_namespace ON storage_object(tenant_id, namespace, status, create_time);

CREATE INDEX idx_storage_object_checksum ON storage_object(tenant_id, namespace, checksum);

CREATE TABLE storage_upload_session(
    session_id CHARACTER VARYING(64) NOT NULL,
    tenant_id BIGINT NOT NULL,
    space_id BIGINT DEFAULT NULL,
    namespace CHARACTER VARYING(255) NOT NULL,
    file_name CHARACTER VARYING(512) NOT NULL,
    content_type CHARACTER VARYING(128) DEFAULT 'application/octet-stream',
    expected_size BIGINT NOT NULL,
    expected_checksum CHARACTER VARYING(64) DEFAULT NULL,
    total_chunks INTEGER NOT NULL,
    status CHARACTER VARYING(20) DEFAULT 'UPLOADING' NOT NULL,
    temp_path CHARACTER VARYING(1024) DEFAULT NULL,
    error_message CHARACTER VARYING(2000) DEFAULT NULL,
    last_heartbeat TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    expires_at TIMESTAMP DEFAULT NULL,
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_storage_upload_session PRIMARY KEY(session_id)
);

CREATE INDEX idx_storage_upload_session_tenant ON storage_upload_session(tenant_id, status, update_time);

CREATE TABLE storage_upload_chunk(
    session_id CHARACTER VARYING(64) NOT NULL,
    chunk_index INTEGER NOT NULL,
    chunk_size BIGINT DEFAULT 0 NOT NULL,
    chunk_checksum CHARACTER VARYING(64) DEFAULT NULL,
    status CHARACTER VARYING(20) DEFAULT 'UPLOADED' NOT NULL,
    uploaded_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_storage_upload_chunk PRIMARY KEY(session_id, chunk_index)
);

-- Source: modules/infrastructure/shiyu-common-core/src/main/resources/db/baseline/h2/schema/common/02_common.sql
-- Final H2 schema baseline. Generated from the validated schema; do not add migrations here.

CREATE TABLE common_dict(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    dict_type CHARACTER VARYING(100) NOT NULL,
    dict_label CHARACTER VARYING(100) NOT NULL,
    dict_value CHARACTER VARYING(100) NOT NULL,
    tenant_id BIGINT NOT NULL,
    dict_sort INTEGER DEFAULT 0,
    css_class CHARACTER VARYING(100),
    list_class CHARACTER VARYING(100),
    is_default CHARACTER(1) DEFAULT 'N',
    status SMALLINT DEFAULT 1,
    remark CHARACTER VARYING(500),
    create_by CHARACTER VARYING(64),
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_by CHARACTER VARYING(64),
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    del_flag SMALLINT DEFAULT 0,
    CONSTRAINT pk_common_dict PRIMARY KEY(id)
);

CREATE INDEX idx_dict_type ON common_dict(dict_type);

CREATE INDEX idx_dict_sort ON common_dict(dict_sort);

CREATE INDEX idx_common_dict_tenant ON common_dict(tenant_id);

-- Source: modules/domains/iam/shiyu-iam-implementation/src/main/resources/db/baseline/h2/schema/iam/03_auth.sql
-- Final H2 schema baseline. Generated from the validated schema; do not add migrations here.

CREATE TABLE auth_tenant(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    parent_id BIGINT DEFAULT NULL,
    code CHARACTER VARYING(64) NOT NULL,
    name CHARACTER VARYING(128),
    contact_name CHARACTER VARYING(64),
    contact_phone CHARACTER VARYING(20),
    address CHARACTER VARYING(255),
    domain CHARACTER VARYING(255),
    intro CHARACTER VARYING(500),
    order INTEGER DEFAULT 0,
    leader CHARACTER VARYING(64),
    phone CHARACTER VARYING(20),
    email CHARACTER VARYING(128),
    remark CHARACTER VARYING(500),
    status SMALLINT DEFAULT 1,
    del_flag SMALLINT DEFAULT 0,
    create_by CHARACTER VARYING(64),
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_by CHARACTER VARYING(64),
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_auth_tenant PRIMARY KEY(id)
);

CREATE INDEX idx_tenant_code ON auth_tenant(code);

CREATE TABLE auth_user(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username CHARACTER VARYING(64) NOT NULL,
    password CHARACTER VARYING(255),
    status SMALLINT DEFAULT 1,
    del_flag SMALLINT DEFAULT 0,
    create_by CHARACTER VARYING(64),
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_by CHARACTER VARYING(64),
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    nick_name CHARACTER VARYING(64),
    gender CHARACTER VARYING(10),
    avatar CHARACTER VARYING(255),
    address CHARACTER VARYING(255),
    email CHARACTER VARYING(128),
    phone CHARACTER VARYING(20),
    remark CHARACTER VARYING(500),
    ext_info CHARACTER VARYING,
    CONSTRAINT pk_auth_user PRIMARY KEY(id)
);

CREATE INDEX idx_username ON auth_user(username);

CREATE TABLE auth_role(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    code CHARACTER VARYING(64) NOT NULL,
    name CHARACTER VARYING(64) NOT NULL,
    tenant_id BIGINT NOT NULL,
    status SMALLINT DEFAULT 1,
    remark CHARACTER VARYING(500),
    del_flag SMALLINT DEFAULT 0,
    create_by CHARACTER VARYING(64),
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_by CHARACTER VARYING(64),
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_auth_role PRIMARY KEY(id)
);

CREATE INDEX idx_code ON auth_role(code);

CREATE TABLE auth_menu(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name CHARACTER VARYING(64) NOT NULL,
    code CHARACTER VARYING(64) NOT NULL,
    type CHARACTER VARYING(20) NOT NULL,
    parent_id BIGINT,
    tenant_id BIGINT NOT NULL,
    path CHARACTER VARYING(255),
    redirect CHARACTER VARYING(255),
    icon CHARACTER VARYING(64),
    component CHARACTER VARYING(255),
    layout CHARACTER VARYING(64),
    keep_alive BOOLEAN,
    method CHARACTER VARYING(20),
    description CHARACTER VARYING(255),
    show BOOLEAN DEFAULT TRUE,
    status SMALLINT DEFAULT 1,
    order INTEGER DEFAULT 0,
    del_flag SMALLINT DEFAULT 0,
    create_by CHARACTER VARYING(64),
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_by CHARACTER VARYING(64),
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_auth_menu PRIMARY KEY(id)
);

CREATE INDEX idx_parent_id ON auth_menu(parent_id);

CREATE TABLE auth_user_scope_role(
    user_id BIGINT NOT NULL,
    role_id BIGINT NOT NULL,
    tenant_id BIGINT NOT NULL,
    status SMALLINT DEFAULT 1,
    del_flag SMALLINT DEFAULT 0,
    create_by CHARACTER VARYING(64),
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_by CHARACTER VARYING(64),
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_auth_user_scope_role PRIMARY KEY(user_id, tenant_id, role_id)
);

CREATE INDEX idx_usr_role ON auth_user_scope_role(role_id);

CREATE TABLE auth_role_scope_menu(
    role_id BIGINT NOT NULL,
    menu_id BIGINT NOT NULL,
    tenant_id BIGINT NOT NULL,
    status SMALLINT DEFAULT 1,
    del_flag SMALLINT DEFAULT 0,
    create_by CHARACTER VARYING(64),
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_by CHARACTER VARYING(64),
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_auth_role_scope_menu PRIMARY KEY(role_id, tenant_id, menu_id)
);

CREATE INDEX idx_rsm_menu_id ON auth_role_scope_menu(menu_id);

CREATE TABLE auth_auth_code(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    code CHARACTER VARYING(64) NOT NULL,
    name CHARACTER VARYING(128),
    status SMALLINT DEFAULT 1,
    del_flag SMALLINT DEFAULT 0,
    create_by CHARACTER VARYING(64),
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_by CHARACTER VARYING(64),
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_auth_auth_code PRIMARY KEY(id),
    CONSTRAINT uk_auth_code_code UNIQUE  (code)
);

CREATE INDEX idx_auth_code ON auth_auth_code(code);

CREATE TABLE auth_role_scope_auth_code(
    role_id BIGINT NOT NULL,
    auth_code_id BIGINT NOT NULL,
    tenant_id BIGINT NOT NULL,
    status SMALLINT DEFAULT 1,
    del_flag SMALLINT DEFAULT 0,
    create_by CHARACTER VARYING(64),
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_by CHARACTER VARYING(64),
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_auth_role_scope_auth_code PRIMARY KEY(role_id, tenant_id, auth_code_id)
);

CREATE INDEX idx_rsac_auth_code ON auth_role_scope_auth_code(auth_code_id);

CREATE TABLE auth_tenant_menu(
    tenant_id BIGINT NOT NULL,
    menu_id BIGINT NOT NULL,
    status SMALLINT DEFAULT 1,
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_auth_tenant_menu PRIMARY KEY(tenant_id, menu_id)
);

CREATE INDEX idx_tenant_menu_menu ON auth_tenant_menu(menu_id);

CREATE TABLE auth_tenant_auth_code(
    tenant_id BIGINT NOT NULL,
    auth_code_id BIGINT NOT NULL,
    status SMALLINT DEFAULT 1,
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_auth_tenant_auth_code PRIMARY KEY(tenant_id, auth_code_id)
);

CREATE INDEX idx_tenant_auth_code_code ON auth_tenant_auth_code(auth_code_id);

CREATE INDEX idx_auth_role_tenant ON auth_role(tenant_id);
CREATE INDEX idx_auth_menu_tenant ON auth_menu(tenant_id);
CREATE INDEX idx_auth_user_scope_role_tenant ON auth_user_scope_role(tenant_id);
CREATE INDEX idx_auth_role_scope_menu_tenant ON auth_role_scope_menu(tenant_id);
CREATE INDEX idx_auth_role_scope_auth_code_tenant ON auth_role_scope_auth_code(tenant_id);
CREATE INDEX idx_auth_tenant_menu_tenant ON auth_tenant_menu(tenant_id);
CREATE INDEX idx_auth_tenant_auth_code_tenant ON auth_tenant_auth_code(tenant_id);

-- Source: modules/domains/agent/shiyu-agent-implementation/src/main/resources/db/baseline/h2/schema/agent/04_agent.sql
-- Final H2 schema baseline. Generated from the validated schema; do not add migrations here.

CREATE TABLE agent_def(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    agent_id CHARACTER VARYING(64) NOT NULL,
    name CHARACTER VARYING(100) NOT NULL,
    description CHARACTER VARYING(500) DEFAULT NULL,
    tenant_id BIGINT NOT NULL,
    owner_id BIGINT DEFAULT NULL,
    current_version CHARACTER VARYING(32) DEFAULT NULL,
    status SMALLINT DEFAULT 1,
    ext_info TEXT DEFAULT NULL,
    del_flag SMALLINT DEFAULT 0,
    create_by CHARACTER VARYING(64) DEFAULT NULL,
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_by CHARACTER VARYING(64) DEFAULT NULL,
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_agent_def PRIMARY KEY(id)
);

CREATE INDEX idx_agent_def_agent_id ON agent_def(agent_id);

CREATE TABLE agent_version(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    agent_id CHARACTER VARYING(64) NOT NULL,
    version_number CHARACTER VARYING(32) NOT NULL,
    tenant_id BIGINT NOT NULL,
    description CHARACTER VARYING(500) DEFAULT NULL,
    status SMALLINT DEFAULT 0,
    graph_config TEXT DEFAULT NULL,
    canvas_config TEXT DEFAULT NULL,
    ext_info TEXT DEFAULT NULL,
    del_flag CHARACTER(1) DEFAULT '0',
    create_by CHARACTER VARYING(64) DEFAULT NULL,
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_by CHARACTER VARYING(64) DEFAULT NULL,
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_agent_version PRIMARY KEY(id)
);

CREATE INDEX idx_agent_version ON agent_version(agent_id, version_number);

CREATE TABLE agent_intent_def(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    agent_id CHARACTER VARYING(64) DEFAULT 'default' NOT NULL,
    code CHARACTER VARYING(64) NOT NULL,
    name CHARACTER VARYING(100) NOT NULL,
    tenant_id BIGINT NOT NULL,
    description CHARACTER VARYING(500) DEFAULT NULL,
    category CHARACTER VARYING(64) DEFAULT 'CONVERSATION',
    priority INTEGER DEFAULT 50,
    confidence_threshold DOUBLE PRECISION DEFAULT 0.75,
    examples CHARACTER VARYING DEFAULT NULL,
    target_node CHARACTER VARYING(64) DEFAULT NULL,
    require_slot_filling CHARACTER(1) DEFAULT '0',
    slots CHARACTER VARYING DEFAULT NULL,
    parameter_mapping CHARACTER VARYING DEFAULT NULL,
    slot_defaults CHARACTER VARYING DEFAULT NULL,
    enabled CHARACTER(1) DEFAULT '1',
    status SMALLINT DEFAULT 1,
    del_flag SMALLINT DEFAULT 0,
    create_by CHARACTER VARYING(64) DEFAULT NULL,
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_by CHARACTER VARYING(64) DEFAULT NULL,
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_agent_intent_def PRIMARY KEY(id)
);

CREATE INDEX idx_intent_def_code_agent ON agent_intent_def(agent_id, code);

CREATE TABLE agent_execution(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1)  NOT NULL,
    execution_id CHARACTER VARYING(64) NOT NULL,
    agent_id CHARACTER VARYING(64) NOT NULL,
    version CHARACTER VARYING(32) DEFAULT NULL,
    user_id BIGINT DEFAULT NULL,
    session_id CHARACTER VARYING(64) DEFAULT NULL,
    tenant_id BIGINT NOT NULL,
    node_id CHARACTER VARYING(64) DEFAULT NULL,
    node_type CHARACTER VARYING(32) DEFAULT NULL,
    input_data CHARACTER VARYING DEFAULT NULL,
    output_data CHARACTER VARYING DEFAULT NULL,
    status SMALLINT DEFAULT 0 NOT NULL,
    error_message CHARACTER VARYING DEFAULT NULL,
    start_time TIMESTAMP NOT NULL,
    end_time TIMESTAMP DEFAULT NULL,
    duration_ms BIGINT DEFAULT NULL,
    create_by CHARACTER VARYING(64) DEFAULT NULL,
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_by CHARACTER VARYING(64) DEFAULT NULL,
    update_time TIMESTAMP DEFAULT NULL,
    del_flag SMALLINT DEFAULT 0,
    CONSTRAINT pk_agent_execution PRIMARY KEY(id)
);

CREATE INDEX idx_agent_exec_exec_id ON agent_execution(execution_id);

CREATE INDEX idx_agent_exec_agent ON agent_execution(agent_id, create_time);

CREATE INDEX idx_agent_exec_session ON agent_execution(session_id);

CREATE TABLE agent_node_execution(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1)  NOT NULL,
    execution_id CHARACTER VARYING(64) NOT NULL,
    node_id CHARACTER VARYING(64) NOT NULL,
    node_type CHARACTER VARYING(32) NOT NULL,
    status SMALLINT DEFAULT 0 NOT NULL,
    input_data CHARACTER VARYING DEFAULT NULL,
    output_data CHARACTER VARYING DEFAULT NULL,
    error_message CHARACTER VARYING DEFAULT NULL,
    start_time TIMESTAMP NOT NULL,
    end_time TIMESTAMP DEFAULT NULL,
    duration_ms BIGINT DEFAULT NULL,
    retry_count INTEGER DEFAULT 0,
    tenant_id BIGINT NOT NULL,
    create_by CHARACTER VARYING(64) DEFAULT NULL,
    update_by CHARACTER VARYING(64) DEFAULT NULL,
    del_flag SMALLINT DEFAULT 0,
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_agent_node_execution PRIMARY KEY(id)
);

CREATE INDEX idx_node_exec_tenant_exec_id ON agent_node_execution(tenant_id, execution_id);

CREATE INDEX idx_node_exec_node_id ON agent_node_execution(node_id);

CREATE TABLE agent_checkpoint(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1)  NOT NULL,
    tenant_id BIGINT NOT NULL,
    checkpoint_id CHARACTER VARYING(64) NOT NULL,
    execution_id CHARACTER VARYING(64) NOT NULL,
    node_id CHARACTER VARYING(64) NOT NULL,
    state_data CHARACTER VARYING DEFAULT NULL,
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_agent_checkpoint PRIMARY KEY(id)
);

CREATE INDEX idx_ckpt_tenant_checkpoint_id ON agent_checkpoint(tenant_id, checkpoint_id);

CREATE INDEX idx_ckpt_tenant_execution_id ON agent_checkpoint(tenant_id, execution_id);

CREATE TABLE agent_eval_dataset(
    id CHARACTER VARYING(64) NOT NULL,
    tenant_id BIGINT NOT NULL,
    owner_user_id BIGINT NOT NULL,
    name CHARACTER VARYING(255) NOT NULL,
    description TEXT,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT pk_agent_eval_dataset PRIMARY KEY (id)
);

CREATE TABLE agent_eval_case(
    id CHARACTER VARYING(64) NOT NULL,
    dataset_id CHARACTER VARYING(64) NOT NULL,
    tenant_id BIGINT NOT NULL,
    input_text TEXT NOT NULL,
    expected_text TEXT,
    metadata_json TEXT,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT pk_agent_eval_case PRIMARY KEY (id)
);

CREATE INDEX idx_agent_eval_case_dataset ON agent_eval_case(tenant_id, dataset_id);

CREATE TABLE agent_eval_run(
    id CHARACTER VARYING(64) NOT NULL,
    dataset_id CHARACTER VARYING(64) NOT NULL,
    tenant_id BIGINT NOT NULL,
    owner_user_id BIGINT NOT NULL,
    app_version_id CHARACTER VARYING(64),
    metric CHARACTER VARYING(48) NOT NULL,
    status CHARACTER VARYING(24) NOT NULL,
    pass_rate DOUBLE PRECISION NOT NULL DEFAULT 0,
    results_json TEXT,
    created_at TIMESTAMP NOT NULL,
    completed_at TIMESTAMP,
    CONSTRAINT pk_agent_eval_run PRIMARY KEY (id)
);

CREATE INDEX idx_agent_def_tenant ON agent_def(tenant_id);
CREATE INDEX idx_agent_version_tenant ON agent_version(tenant_id);
CREATE INDEX idx_agent_intent_def_tenant ON agent_intent_def(tenant_id);
CREATE INDEX idx_agent_execution_tenant ON agent_execution(tenant_id);
CREATE INDEX idx_agent_eval_dataset_tenant ON agent_eval_dataset(tenant_id);
CREATE INDEX idx_agent_eval_run_tenant ON agent_eval_run(tenant_id);

-- Source: modules/domains/model/shiyu-model-implementation/src/main/resources/db/baseline/h2/schema/model/04_model.sql
-- Final H2 schema baseline. Generated from the validated schema; do not add migrations here.

CREATE TABLE model_ai_platform(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name CHARACTER VARYING(50) NOT NULL,
    code CHARACTER VARYING(50) NOT NULL,
    adapter_type CHARACTER VARYING(32) DEFAULT 'OPENAI_COMPATIBLE' NOT NULL,
    tenant_id BIGINT NOT NULL,
    base_url CHARACTER VARYING(500) DEFAULT NULL,
    api_key CHARACTER VARYING(500) DEFAULT NULL,
    temperature DOUBLE PRECISION DEFAULT 0.7,
    max_tokens INTEGER DEFAULT 4096,
    max_retries INTEGER DEFAULT 3,
    available_models CHARACTER VARYING DEFAULT NULL,
    extra_config CHARACTER VARYING DEFAULT NULL,
    is_default CHARACTER(1) DEFAULT 'N',
    status SMALLINT DEFAULT 1,
    remark CHARACTER VARYING(500) DEFAULT NULL,
    ext_info TEXT DEFAULT NULL,
    create_by CHARACTER VARYING(64) DEFAULT NULL,
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_by CHARACTER VARYING(64) DEFAULT NULL,
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    del_flag SMALLINT DEFAULT 0,
    CONSTRAINT pk_model_ai_platform PRIMARY KEY(id)
);

CREATE INDEX idx_model_ai_platform_code ON model_ai_platform(code);

CREATE TABLE model_ai_model(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    platform_id BIGINT NOT NULL,
    model_name CHARACTER VARYING(100) NOT NULL,
    tenant_id BIGINT NOT NULL,
    display_name CHARACTER VARYING(100) DEFAULT NULL,
    description CHARACTER VARYING(500) DEFAULT NULL,
    model_config CHARACTER VARYING DEFAULT NULL,
    is_default CHARACTER(1) DEFAULT 'N',
    status SMALLINT DEFAULT 1,
    sort INTEGER DEFAULT 0,
    create_by CHARACTER VARYING(64) DEFAULT NULL,
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_by CHARACTER VARYING(64) DEFAULT NULL,
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    del_flag SMALLINT DEFAULT 0,
    CONSTRAINT pk_model_ai_model PRIMARY KEY(id)
);

CREATE INDEX idx_model_ai_model_platform_id ON model_ai_model(platform_id);
CREATE INDEX idx_model_ai_platform_tenant ON model_ai_platform(tenant_id);
CREATE INDEX idx_model_ai_model_tenant ON model_ai_model(tenant_id);

-- Source: modules/domains/governance/shiyu-governance-implementation/src/main/resources/db/baseline/h2/schema/governance/05_governance.sql
-- Governance-owned v4 schema. No cross-domain foreign keys or joins.

CREATE TABLE governance_usage_record (
    id CHARACTER VARYING(64) NOT NULL,
    tenant_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    correlation_id CHARACTER VARYING(128) NOT NULL,
    source_type CHARACTER VARYING(64) NOT NULL,
    source_id CHARACTER VARYING(128) NOT NULL,
    input_tokens BIGINT DEFAULT 0 NOT NULL,
    output_tokens BIGINT DEFAULT 0 NOT NULL,
    cost DECIMAL(20, 8) DEFAULT 0 NOT NULL,
    occurred_at TIMESTAMP NOT NULL,
    usage_type CHARACTER VARYING(32) DEFAULT 'METERED' NOT NULL,
    latency_ms BIGINT,
    session_id CHARACTER VARYING(128),
    ext_info TEXT,
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT pk_governance_usage_record PRIMARY KEY (id),
    CONSTRAINT uk_governance_usage_source UNIQUE (tenant_id, source_type, source_id),
    CONSTRAINT ck_governance_usage_input CHECK (input_tokens >= 0),
    CONSTRAINT ck_governance_usage_output CHECK (output_tokens >= 0),
    CONSTRAINT ck_governance_usage_cost CHECK (cost >= 0)
);

CREATE INDEX idx_governance_usage_tenant_time
    ON governance_usage_record (tenant_id, occurred_at);

CREATE INDEX idx_governance_usage_tenant_user_time
    ON governance_usage_record (tenant_id, user_id, occurred_at);

-- Source: modules/domains/knowledge/shiyu-knowledge-implementation/src/main/resources/db/baseline/h2/schema/knowledge/06_knowledge.sql
-- Final H2 schema baseline. Generated from the validated schema; do not add migrations here.

CREATE TABLE knowledge_relation(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY  NOT NULL,
    source_id BIGINT NOT NULL,
    target_id BIGINT NOT NULL,
    relation_type CHARACTER VARYING(20) NOT NULL,
    weight DOUBLE PRECISION DEFAULT 1.0,
    tenant_id BIGINT NOT NULL,
    status SMALLINT DEFAULT 1,
    del_flag SMALLINT DEFAULT 0,
    create_by CHARACTER VARYING(64) DEFAULT NULL,
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_by CHARACTER VARYING(64) DEFAULT NULL,
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    space_id BIGINT DEFAULT NULL,
    CONSTRAINT pk_knowledge_relation PRIMARY KEY(id)
);

CREATE UNIQUE  INDEX uk_knowledge_relation_tenant_space_edge ON knowledge_relation(tenant_id, space_id, source_id, target_id, relation_type);

CREATE INDEX idx_knowledge_relation_space ON knowledge_relation(tenant_id, space_id);

CREATE INDEX idx_kr_source ON knowledge_relation(tenant_id, source_id);

CREATE INDEX idx_kr_target ON knowledge_relation(tenant_id, target_id);

CREATE TABLE knowledge_document_version(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY  NOT NULL,
    document_id BIGINT NOT NULL,
    space_id BIGINT NOT NULL,
    version_no INTEGER NOT NULL,
    title CHARACTER VARYING(255) NOT NULL,
    content TEXT DEFAULT NULL,
    storage_provider CHARACTER VARYING(32) DEFAULT 'local',
    object_key CHARACTER VARYING(1024) DEFAULT NULL,
    mime_type CHARACTER VARYING(128) DEFAULT NULL,
    file_size BIGINT DEFAULT 0,
    checksum CHARACTER VARYING(64) DEFAULT NULL,
    lifecycle_status CHARACTER VARYING(20) DEFAULT 'DRAFT',
    parse_status CHARACTER VARYING(20) DEFAULT 'PENDING',
    model_profile CHARACTER VARYING(100) DEFAULT 'default',
    published_at TIMESTAMP DEFAULT NULL,
    tenant_id BIGINT NOT NULL,
    status SMALLINT DEFAULT 1,
    del_flag SMALLINT DEFAULT 0,
    create_by CHARACTER VARYING(64) DEFAULT NULL,
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_by CHARACTER VARYING(64) DEFAULT NULL,
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    storage_object_id BIGINT DEFAULT NULL,
    CONSTRAINT pk_knowledge_document_version PRIMARY KEY(id)
);

CREATE UNIQUE  INDEX uk_knowledge_document_version ON knowledge_document_version(tenant_id, document_id, version_no);

CREATE INDEX idx_knowledge_document_version_space ON knowledge_document_version(tenant_id, space_id, lifecycle_status);

CREATE TABLE knowledge_document(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title CHARACTER VARYING(255) NOT NULL,
    content CHARACTER VARYING NOT NULL,
    doc_type CHARACTER VARYING(20) DEFAULT 'ARTICLE',
    source CHARACTER VARYING(255) DEFAULT NULL,
    author CHARACTER VARYING(128) DEFAULT NULL,
    tenant_id BIGINT NOT NULL,
    status SMALLINT DEFAULT 1,
    del_flag SMALLINT DEFAULT 0,
    create_by CHARACTER VARYING(64) DEFAULT NULL,
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_by CHARACTER VARYING(64) DEFAULT NULL,
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    space_id BIGINT DEFAULT NULL,
    current_version_id BIGINT DEFAULT NULL,
    lifecycle_status CHARACTER VARYING(20) DEFAULT 'PUBLISHED',
    parse_status CHARACTER VARYING(20) DEFAULT 'READY',
    storage_provider CHARACTER VARYING(32) DEFAULT 'local',
    storage_object_id BIGINT DEFAULT NULL,
    object_key CHARACTER VARYING(1024) DEFAULT NULL,
    mime_type CHARACTER VARYING(128) DEFAULT NULL,
    file_size BIGINT DEFAULT 0,
    checksum CHARACTER VARYING(64) DEFAULT NULL,
    CONSTRAINT pk_knowledge_document PRIMARY KEY(id)
);

CREATE INDEX idx_kd_type ON knowledge_document(tenant_id, doc_type);

CREATE INDEX idx_knowledge_document_space ON knowledge_document(tenant_id, space_id, lifecycle_status);

CREATE TABLE knowledge_document_relation(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1)  NOT NULL,
    tenant_id BIGINT NOT NULL,
    space_id BIGINT NOT NULL,
    source_document_id BIGINT NOT NULL,
    target_document_id BIGINT NOT NULL,
    relation_type CHARACTER VARYING(32) NOT NULL,
    status SMALLINT DEFAULT 1,
    del_flag SMALLINT DEFAULT 0,
    create_by CHARACTER VARYING(64) DEFAULT NULL,
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_by CHARACTER VARYING(64) DEFAULT NULL,
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_knowledge_document_relation PRIMARY KEY(id)
);

CREATE UNIQUE  INDEX uk_knowledge_document_relation ON knowledge_document_relation(tenant_id, space_id, source_document_id, target_document_id, relation_type);

CREATE INDEX idx_knowledge_document_relation_source ON knowledge_document_relation(tenant_id, space_id, source_document_id);

CREATE INDEX idx_knowledge_document_relation_target ON knowledge_document_relation(tenant_id, space_id, target_document_id);

CREATE TABLE knowledge_doc_relation(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY  NOT NULL,
    space_id BIGINT DEFAULT NULL,
    doc_id BIGINT NOT NULL,
    knowledge_id BIGINT NOT NULL,
    relation_type CHARACTER VARYING(20) DEFAULT 'RELATED',
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    tenant_id BIGINT NOT NULL,
    create_by CHARACTER VARYING(64) DEFAULT NULL,
    update_by CHARACTER VARYING(64) DEFAULT NULL,
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    status SMALLINT DEFAULT 1,
    del_flag SMALLINT DEFAULT 0,
    CONSTRAINT pk_knowledge_doc_relation PRIMARY KEY(id)
);

CREATE INDEX idx_kdr_knowledge ON knowledge_doc_relation(tenant_id, knowledge_id);

CREATE UNIQUE  INDEX uk_knowledge_doc_relation_tenant ON knowledge_doc_relation(tenant_id, doc_id, knowledge_id);

CREATE TABLE knowledge_base(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    code CHARACTER VARYING(50) NOT NULL,
    name CHARACTER VARYING(200) NOT NULL,
    description CHARACTER VARYING DEFAULT NULL,
    difficulty SMALLINT DEFAULT 2,
    category CHARACTER VARYING(64) DEFAULT NULL,
    tags CHARACTER VARYING(500) DEFAULT NULL,
    tenant_id BIGINT NOT NULL,
    status SMALLINT DEFAULT 1,
    del_flag SMALLINT DEFAULT 0,
    create_by CHARACTER VARYING(64) DEFAULT NULL,
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_by CHARACTER VARYING(64) DEFAULT NULL,
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    space_id BIGINT DEFAULT NULL,
    difficulty_level INTEGER DEFAULT NULL,
    CONSTRAINT pk_knowledge_base PRIMARY KEY(id)
);

CREATE INDEX idx_knowledge_category ON knowledge_base(category);

CREATE UNIQUE  INDEX uk_knowledge_base_tenant_space_code ON knowledge_base(tenant_id, space_id, code);

CREATE INDEX idx_knowledge_base_space ON knowledge_base(tenant_id, space_id);

CREATE TABLE knowledge_space_member(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY  NOT NULL,
    space_id BIGINT NOT NULL,
    principal_type CHARACTER VARYING(16) NOT NULL,
    principal_id BIGINT NOT NULL,
    space_role CHARACTER VARYING(16) NOT NULL,
    tenant_id BIGINT NOT NULL,
    status SMALLINT DEFAULT 1,
    del_flag SMALLINT DEFAULT 0,
    create_by CHARACTER VARYING(64) DEFAULT NULL,
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_by CHARACTER VARYING(64) DEFAULT NULL,
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_knowledge_space_member PRIMARY KEY(id)
);

CREATE UNIQUE  INDEX uk_knowledge_space_member ON knowledge_space_member(tenant_id, space_id, principal_type, principal_id);

CREATE TABLE knowledge_review_record(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY  NOT NULL,
    document_id BIGINT NOT NULL,
    version_id BIGINT NOT NULL,
    action CHARACTER VARYING(20) NOT NULL,
    comment_text CHARACTER VARYING(1000) DEFAULT NULL,
    tenant_id BIGINT NOT NULL,
    status SMALLINT DEFAULT 1,
    del_flag SMALLINT DEFAULT 0,
    create_by CHARACTER VARYING(64) DEFAULT NULL,
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_by CHARACTER VARYING(64) DEFAULT NULL,
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_knowledge_review_record PRIMARY KEY(id)
);

CREATE TABLE knowledge_ingestion_job(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY  NOT NULL,
    job_key CHARACTER VARYING(128) NOT NULL,
    job_type CHARACTER VARYING(32) NOT NULL,
    space_id BIGINT NOT NULL,
    document_id BIGINT DEFAULT NULL,
    version_id BIGINT DEFAULT NULL,
    actor_user_id BIGINT DEFAULT NULL,
    job_status CHARACTER VARYING(20) DEFAULT 'PENDING',
    stage CHARACTER VARYING(32) DEFAULT 'QUEUED',
    progress INTEGER DEFAULT 0,
    attempts INTEGER DEFAULT 0,
    max_attempts INTEGER DEFAULT 3,
    error_message CHARACTER VARYING(2000) DEFAULT NULL,
    checkpoint_data TEXT DEFAULT NULL,
    heartbeat_time TIMESTAMP DEFAULT NULL,
    started_time TIMESTAMP DEFAULT NULL,
    finished_time TIMESTAMP DEFAULT NULL,
    lock_version BIGINT DEFAULT 0,
    tenant_id BIGINT NOT NULL,
    status SMALLINT DEFAULT 1,
    del_flag SMALLINT DEFAULT 0,
    create_by CHARACTER VARYING(64) DEFAULT NULL,
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_by CHARACTER VARYING(64) DEFAULT NULL,
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_knowledge_ingestion_job PRIMARY KEY(id)
);

CREATE UNIQUE  INDEX uk_knowledge_ingestion_job_key ON knowledge_ingestion_job(tenant_id, job_key);

CREATE INDEX idx_knowledge_ingestion_job_poll ON knowledge_ingestion_job(tenant_id, job_status, create_time);

CREATE TABLE knowledge_audit_log(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY  NOT NULL,
    space_id BIGINT DEFAULT NULL,
    resource_type CHARACTER VARYING(32) NOT NULL,
    resource_id BIGINT DEFAULT NULL,
    action CHARACTER VARYING(32) NOT NULL,
    detail_json TEXT DEFAULT NULL,
    tenant_id BIGINT NOT NULL,
    status SMALLINT DEFAULT 1,
    del_flag SMALLINT DEFAULT 0,
    create_by CHARACTER VARYING(64) DEFAULT NULL,
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_by CHARACTER VARYING(64) DEFAULT NULL,
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_knowledge_audit_log PRIMARY KEY(id)
);

CREATE INDEX idx_knowledge_audit_resource ON knowledge_audit_log(tenant_id, resource_type, resource_id);

CREATE TABLE knowledge_evaluation_case(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY  NOT NULL,
    space_id BIGINT NOT NULL,
    question TEXT NOT NULL,
    expected_doc_ids CHARACTER VARYING(2000) DEFAULT NULL,
    expected_answer TEXT DEFAULT NULL,
    tenant_id BIGINT NOT NULL,
    status SMALLINT DEFAULT 1,
    del_flag SMALLINT DEFAULT 0,
    create_by CHARACTER VARYING(64) DEFAULT NULL,
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_by CHARACTER VARYING(64) DEFAULT NULL,
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_knowledge_evaluation_case PRIMARY KEY(id)
);

CREATE TABLE knowledge_difficulty_scale(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY  NOT NULL,
    code CHARACTER VARYING(64) NOT NULL,
    name CHARACTER VARYING(128) NOT NULL,
    description CHARACTER VARYING(500) DEFAULT NULL,
    level_count INTEGER DEFAULT 5 NOT NULL,
    tenant_id BIGINT NOT NULL,
    status SMALLINT DEFAULT 1,
    del_flag SMALLINT DEFAULT 0,
    create_by CHARACTER VARYING(64) DEFAULT NULL,
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_by CHARACTER VARYING(64) DEFAULT NULL,
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_knowledge_difficulty_scale PRIMARY KEY(id)
);

CREATE UNIQUE  INDEX uk_knowledge_difficulty_scale_tenant_code ON knowledge_difficulty_scale(tenant_id, code);

CREATE TABLE knowledge_difficulty_scale_level(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY  NOT NULL,
    scale_id BIGINT NOT NULL,
    level INTEGER NOT NULL,
    label CHARACTER VARYING(128) NOT NULL,
    description CHARACTER VARYING(500) DEFAULT NULL,
    tenant_id BIGINT NOT NULL,
    status SMALLINT DEFAULT 1,
    del_flag SMALLINT DEFAULT 0,
    create_by CHARACTER VARYING(64) DEFAULT NULL,
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_by CHARACTER VARYING(64) DEFAULT NULL,
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_knowledge_difficulty_scale_level PRIMARY KEY(id)
);

CREATE UNIQUE  INDEX uk_knowledge_difficulty_scale_level ON knowledge_difficulty_scale_level(tenant_id, scale_id, level);

CREATE TABLE knowledge_space(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY  NOT NULL,
    code CHARACTER VARYING(64) NOT NULL,
    name CHARACTER VARYING(200) NOT NULL,
    description CHARACTER VARYING DEFAULT NULL,
    access_mode CHARACTER VARYING(20) DEFAULT 'PRIVATE',
    review_mode CHARACTER VARYING(20) DEFAULT 'OPTIONAL',
    embedding_profile CHARACTER VARYING(100) DEFAULT 'default',
    rerank_profile CHARACTER VARYING(100) DEFAULT 'default',
    chunk_strategy CHARACTER VARYING(32) DEFAULT 'HEADING',
    chunk_size INTEGER DEFAULT 800,
    chunk_overlap INTEGER DEFAULT 100,
    active_index_version BIGINT DEFAULT 0,
    tenant_id BIGINT NOT NULL,
    status SMALLINT DEFAULT 1,
    del_flag SMALLINT DEFAULT 0,
    create_by CHARACTER VARYING(64) DEFAULT NULL,
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_by CHARACTER VARYING(64) DEFAULT NULL,
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    difficulty_scale_id BIGINT DEFAULT 1,
    binding_mode CHARACTER VARYING(20) DEFAULT 'OPTIONAL',
    domain_code CHARACTER VARYING(32) DEFAULT 'GENERAL' NOT NULL,
    CONSTRAINT pk_knowledge_space PRIMARY KEY(id)
);

CREATE INDEX idx_knowledge_space_member_tenant ON knowledge_space_member(tenant_id);
CREATE INDEX idx_knowledge_review_record_tenant ON knowledge_review_record(tenant_id);
CREATE INDEX idx_knowledge_evaluation_case_tenant ON knowledge_evaluation_case(tenant_id);

CREATE UNIQUE  INDEX uk_knowledge_space_tenant_code ON knowledge_space(tenant_id, code);

-- Source: modules/domains/education/shiyu-education-implementation/src/main/resources/db/baseline/h2/schema/education/07_education.sql
-- Final H2 schema baseline. Generated from the validated schema; do not add migrations here.

CREATE TABLE edu_ability(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY  NOT NULL,
    student_id BIGINT NOT NULL,
    knowledge_id BIGINT NOT NULL,
    remember DOUBLE PRECISION DEFAULT 0,
    understand DOUBLE PRECISION DEFAULT 0,
    apply DOUBLE PRECISION DEFAULT 0,
    analyze DOUBLE PRECISION DEFAULT 0,
    evaluate DOUBLE PRECISION DEFAULT 0,
    create_score DOUBLE PRECISION DEFAULT 0,
    overall_mastery DOUBLE PRECISION DEFAULT 0,
    last_update TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    tenant_id BIGINT NOT NULL,
    status SMALLINT DEFAULT 1,
    del_flag SMALLINT DEFAULT 0,
    create_by CHARACTER VARYING(64),
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_by CHARACTER VARYING(64),
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_edu_ability PRIMARY KEY(id),
    CONSTRAINT uk_ability_tenant_student_knowledge UNIQUE  (tenant_id, student_id, knowledge_id)
);

CREATE TABLE edu_textbook(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY  NOT NULL,
    name CHARACTER VARYING(128) NOT NULL,
    subject_code CHARACTER VARYING(20) NOT NULL,
    grade INTEGER NOT NULL,
    publisher CHARACTER VARYING(64) NOT NULL,
    isbn CHARACTER VARYING(32) DEFAULT NULL,
    tenant_id BIGINT NOT NULL,
    status SMALLINT DEFAULT 1,
    del_flag SMALLINT DEFAULT 0,
    create_by CHARACTER VARYING(64),
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_by CHARACTER VARYING(64),
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_edu_textbook PRIMARY KEY(id)
);

CREATE TABLE edu_chapter(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY  NOT NULL,
    textbook_id BIGINT NOT NULL,
    parent_id BIGINT DEFAULT NULL,
    name CHARACTER VARYING(128) NOT NULL,
    chapter_order INTEGER DEFAULT 0,
    tenant_id BIGINT NOT NULL,
    status SMALLINT DEFAULT 1,
    del_flag SMALLINT DEFAULT 0,
    create_by CHARACTER VARYING(64),
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_by CHARACTER VARYING(64),
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_edu_chapter PRIMARY KEY(id)
);

CREATE INDEX idx_chapter_tenant_textbook ON edu_chapter(tenant_id, textbook_id);

CREATE INDEX idx_chapter_tenant_parent ON edu_chapter(tenant_id, parent_id);

CREATE TABLE edu_knowledge_textbook(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY  NOT NULL,
    knowledge_id BIGINT NOT NULL,
    textbook_id BIGINT NOT NULL,
    chapter_id BIGINT DEFAULT NULL,
    tenant_id BIGINT NOT NULL,
    status SMALLINT DEFAULT 1,
    del_flag SMALLINT DEFAULT 0,
    create_by CHARACTER VARYING(64),
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_by CHARACTER VARYING(64),
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_edu_knowledge_textbook PRIMARY KEY(id),
    CONSTRAINT uk_kt_tenant_knowledge_textbook UNIQUE  (tenant_id, knowledge_id, textbook_id)
);

CREATE TABLE edu_student(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY  NOT NULL,
    user_id BIGINT NOT NULL,
    student_no CHARACTER VARYING(50) DEFAULT NULL,
    name CHARACTER VARYING(100) NOT NULL,
    gender SMALLINT DEFAULT NULL,
    birth_date DATE DEFAULT NULL,
    grade INTEGER NOT NULL,
    grade_level CHARACTER VARYING(10) DEFAULT NULL,
    school CHARACTER VARYING(200) DEFAULT NULL,
    class_name CHARACTER VARYING(50) DEFAULT NULL,
    parent_id BIGINT DEFAULT NULL,
    learning_style CHARACTER VARYING(20) DEFAULT NULL,
    created_at TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    tenant_id BIGINT NOT NULL,
    status SMALLINT DEFAULT 1,
    del_flag SMALLINT DEFAULT 0,
    create_by CHARACTER VARYING(64),
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_by CHARACTER VARYING(64),
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_edu_student PRIMARY KEY(id),
    CONSTRAINT uk_student_tenant_user UNIQUE  (tenant_id, user_id)
);

CREATE INDEX idx_student_tenant_grade ON edu_student(tenant_id, grade);

CREATE TABLE edu_teacher(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY  NOT NULL,
    user_id BIGINT NOT NULL,
    teacher_no CHARACTER VARYING(50) DEFAULT NULL,
    name CHARACTER VARYING(100) NOT NULL,
    subject CHARACTER VARYING(50) DEFAULT NULL,
    school CHARACTER VARYING(200) DEFAULT NULL,
    title CHARACTER VARYING(100) DEFAULT NULL,
    phone CHARACTER VARYING(20) DEFAULT NULL,
    created_at TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP,
    tenant_id BIGINT NOT NULL,
    status SMALLINT DEFAULT 1,
    del_flag SMALLINT DEFAULT 0,
    create_by CHARACTER VARYING(64),
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_by CHARACTER VARYING(64),
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_edu_teacher PRIMARY KEY(id),
    CONSTRAINT uk_teacher_tenant_user UNIQUE  (tenant_id, user_id)
);

CREATE TABLE edu_subject(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY  NOT NULL,
    code CHARACTER VARYING(20) NOT NULL,
    name CHARACTER VARYING(50) NOT NULL,
    grade_level CHARACTER VARYING(10) DEFAULT 'ALL',
    icon CHARACTER VARYING(200) DEFAULT NULL,
    sort_order INTEGER DEFAULT 0,
    status SMALLINT DEFAULT 1,
    tenant_id BIGINT NOT NULL,
    del_flag SMALLINT DEFAULT 0,
    create_by CHARACTER VARYING(64),
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_by CHARACTER VARYING(64),
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_edu_subject PRIMARY KEY(id),
    CONSTRAINT uk_subject_tenant_code UNIQUE  (tenant_id, code)
);

CREATE TABLE edu_course(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY  NOT NULL,
    name CHARACTER VARYING(200) NOT NULL,
    description CHARACTER VARYING DEFAULT NULL,
    subject_code CHARACTER VARYING(20) NOT NULL,
    grade INTEGER DEFAULT NULL,
    textbook_id BIGINT DEFAULT NULL,
    teacher_id BIGINT DEFAULT NULL,
    cover_url CHARACTER VARYING(500) DEFAULT NULL,
    total_hours INTEGER DEFAULT NULL,
    status SMALLINT DEFAULT 1,
    view_count BIGINT DEFAULT 0,
    created_at TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    tenant_id BIGINT NOT NULL,
    del_flag SMALLINT DEFAULT 0,
    create_by CHARACTER VARYING(64),
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_by CHARACTER VARYING(64),
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_edu_course PRIMARY KEY(id)
);

CREATE INDEX idx_course_tenant_subject ON edu_course(tenant_id, subject_code);

CREATE INDEX idx_course_tenant_textbook ON edu_course(tenant_id, textbook_id);

CREATE TABLE edu_course_chapter(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY  NOT NULL,
    course_id BIGINT NOT NULL,
    name CHARACTER VARYING(200) NOT NULL,
    order_no INTEGER NOT NULL,
    created_at TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP,
    tenant_id BIGINT NOT NULL,
    status SMALLINT DEFAULT 1,
    del_flag SMALLINT DEFAULT 0,
    create_by CHARACTER VARYING(64),
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_by CHARACTER VARYING(64),
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_edu_course_chapter PRIMARY KEY(id)
);

CREATE INDEX idx_course_chapter_tenant_course ON edu_course_chapter(tenant_id, course_id);

CREATE TABLE edu_course_section(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY  NOT NULL,
    chapter_id BIGINT NOT NULL,
    name CHARACTER VARYING(200) NOT NULL,
    order_no INTEGER NOT NULL,
    content_url CHARACTER VARYING(500) DEFAULT NULL,
    video_url CHARACTER VARYING(500) DEFAULT NULL,
    duration_min INTEGER DEFAULT NULL,
    created_at TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP,
    tenant_id BIGINT NOT NULL,
    status SMALLINT DEFAULT 1,
    del_flag SMALLINT DEFAULT 0,
    create_by CHARACTER VARYING(64),
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_by CHARACTER VARYING(64),
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_edu_course_section PRIMARY KEY(id)
);

CREATE INDEX idx_course_section_tenant_chapter ON edu_course_section(tenant_id, chapter_id);

CREATE TABLE edu_course_knowledge(
    course_id BIGINT NOT NULL,
    knowledge_id BIGINT NOT NULL,
    section_id BIGINT DEFAULT NULL,
    sort_order INTEGER DEFAULT 0,
    tenant_id BIGINT NOT NULL,
    status SMALLINT DEFAULT 1,
    del_flag SMALLINT DEFAULT 0,
    create_by CHARACTER VARYING(64),
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_by CHARACTER VARYING(64),
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_edu_course_knowledge PRIMARY KEY(course_id, knowledge_id)
);

CREATE INDEX idx_ck_knowledge ON edu_course_knowledge(knowledge_id);

CREATE TABLE edu_resource(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY  NOT NULL,
    name CHARACTER VARYING(200) NOT NULL,
    type CHARACTER VARYING(20) NOT NULL,
    url CHARACTER VARYING(500) NOT NULL,
    size_bytes BIGINT DEFAULT NULL,
    duration_sec INTEGER DEFAULT NULL,
    subject_code CHARACTER VARYING(20) DEFAULT NULL,
    grade INTEGER DEFAULT NULL,
    difficulty SMALLINT DEFAULT NULL,
    cover_url CHARACTER VARYING(500) DEFAULT NULL,
    description CHARACTER VARYING DEFAULT NULL,
    status SMALLINT DEFAULT 1,
    view_count BIGINT DEFAULT 0,
    created_at TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP,
    tenant_id BIGINT NOT NULL,
    del_flag SMALLINT DEFAULT 0,
    create_by CHARACTER VARYING(64),
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_by CHARACTER VARYING(64),
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_edu_resource PRIMARY KEY(id)
);

CREATE INDEX idx_resource_tenant_subject ON edu_resource(tenant_id, subject_code);

CREATE TABLE edu_resource_knowledge(
    resource_id BIGINT NOT NULL,
    knowledge_id BIGINT NOT NULL,
    sort_order INTEGER DEFAULT 0,
    tenant_id BIGINT NOT NULL,
    status SMALLINT DEFAULT 1,
    del_flag SMALLINT DEFAULT 0,
    create_by CHARACTER VARYING(64),
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_by CHARACTER VARYING(64),
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_edu_resource_knowledge PRIMARY KEY(resource_id, knowledge_id)
);

CREATE INDEX idx_rk_knowledge ON edu_resource_knowledge(knowledge_id);

CREATE TABLE edu_question(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY  NOT NULL,
    code CHARACTER VARYING(50) DEFAULT NULL,
    type CHARACTER VARYING(20) NOT NULL,
    subject_code CHARACTER VARYING(20) NOT NULL,
    grade INTEGER NOT NULL,
    difficulty SMALLINT NOT NULL,
    ability_dimension CHARACTER VARYING(20) DEFAULT NULL,
    title CHARACTER VARYING NOT NULL,
    options CHARACTER VARYING DEFAULT NULL,
    answer CHARACTER VARYING NOT NULL,
    analysis CHARACTER VARYING DEFAULT NULL,
    source CHARACTER VARYING(200) DEFAULT NULL,
    tags CHARACTER VARYING DEFAULT NULL,
    status SMALLINT DEFAULT 1,
    used_count BIGINT DEFAULT 0,
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    tenant_id BIGINT NOT NULL,
    del_flag SMALLINT DEFAULT 0,
    create_by CHARACTER VARYING(64),
    update_by CHARACTER VARYING(64),
    CONSTRAINT pk_edu_question PRIMARY KEY(id),
    CONSTRAINT uk_question_tenant_code UNIQUE  (tenant_id, code)
);

CREATE INDEX idx_question_tenant_subject ON edu_question(tenant_id, subject_code);

CREATE INDEX idx_question_tenant_difficulty ON edu_question(tenant_id, difficulty);

CREATE TABLE edu_question_knowledge(
    question_id BIGINT NOT NULL,
    knowledge_id BIGINT NOT NULL,
    weight DOUBLE PRECISION DEFAULT 1.0,
    tenant_id BIGINT NOT NULL,
    status SMALLINT DEFAULT 1,
    del_flag SMALLINT DEFAULT 0,
    create_by CHARACTER VARYING(64),
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_by CHARACTER VARYING(64),
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_edu_question_knowledge PRIMARY KEY(question_id, knowledge_id)
);

CREATE INDEX idx_qk_knowledge ON edu_question_knowledge(knowledge_id);

CREATE TABLE edu_exam(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY  NOT NULL,
    name CHARACTER VARYING(200) NOT NULL,
    type CHARACTER VARYING(20) NOT NULL,
    subject_code CHARACTER VARYING(20) NOT NULL,
    grade INTEGER NOT NULL,
    duration_min INTEGER NOT NULL,
    total_score INTEGER NOT NULL,
    status SMALLINT DEFAULT 0,
    teacher_id BIGINT DEFAULT NULL,
    start_time TIMESTAMP(0) DEFAULT NULL,
    end_time TIMESTAMP(0) DEFAULT NULL,
    created_at TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP,
    tenant_id BIGINT NOT NULL,
    del_flag SMALLINT DEFAULT 0,
    create_by CHARACTER VARYING(64),
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_by CHARACTER VARYING(64),
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_edu_exam PRIMARY KEY(id)
);

CREATE INDEX idx_exam_tenant_subject ON edu_exam(tenant_id, subject_code);

CREATE TABLE edu_exam_section(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY  NOT NULL,
    exam_id BIGINT NOT NULL,
    name CHARACTER VARYING(100) NOT NULL,
    order_no INTEGER NOT NULL,
    score_per_q DECIMAL(5, 2) NOT NULL,
    created_at TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP,
    tenant_id BIGINT NOT NULL,
    status SMALLINT DEFAULT 1,
    del_flag SMALLINT DEFAULT 0,
    create_by CHARACTER VARYING(64),
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_by CHARACTER VARYING(64),
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_edu_exam_section PRIMARY KEY(id)
);

CREATE INDEX idx_exam_section_exam ON edu_exam_section(exam_id);

CREATE TABLE edu_exam_question(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY  NOT NULL,
    exam_id BIGINT NOT NULL,
    section_id BIGINT NOT NULL,
    question_id BIGINT NOT NULL,
    order_no INTEGER NOT NULL,
    score DECIMAL(5, 2) DEFAULT NULL,
    tenant_id BIGINT NOT NULL,
    status SMALLINT DEFAULT 1,
    del_flag SMALLINT DEFAULT 0,
    create_by CHARACTER VARYING(64),
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_by CHARACTER VARYING(64),
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_edu_exam_question PRIMARY KEY(id)
);

CREATE INDEX idx_eq_exam ON edu_exam_question(exam_id);

CREATE INDEX idx_eq_section ON edu_exam_question(section_id);

CREATE INDEX idx_eq_question ON edu_exam_question(question_id);

CREATE TABLE edu_study_record(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1)  NOT NULL,
    student_id BIGINT NOT NULL,
    knowledge_id BIGINT NOT NULL,
    record_type CHARACTER VARYING(20) NOT NULL,
    question_id BIGINT DEFAULT NULL,
    score DOUBLE PRECISION DEFAULT NULL,
    accuracy DOUBLE PRECISION DEFAULT NULL,
    duration_sec INTEGER DEFAULT NULL,
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    tenant_id BIGINT NOT NULL,
    status SMALLINT DEFAULT 1,
    del_flag SMALLINT DEFAULT 0,
    create_by CHARACTER VARYING(64),
    update_by CHARACTER VARYING(64),
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_edu_study_record PRIMARY KEY(id)
);

CREATE INDEX idx_sr_tenant_student ON edu_study_record(tenant_id, student_id);

CREATE INDEX idx_sr_tenant_knowledge ON edu_study_record(tenant_id, knowledge_id);

CREATE TABLE edu_review_task(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY  NOT NULL,
    student_id BIGINT NOT NULL,
    knowledge_id BIGINT NOT NULL,
    review_date DATE NOT NULL,
    review_round INTEGER NOT NULL,
    status SMALLINT DEFAULT 0,
    result_score DOUBLE PRECISION DEFAULT NULL,
    completed_at TIMESTAMP,
    tenant_id BIGINT NOT NULL,
    create_by CHARACTER VARYING(64) DEFAULT NULL,
    update_by CHARACTER VARYING(64) DEFAULT NULL,
    del_flag SMALLINT DEFAULT 0,
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_edu_review_task PRIMARY KEY(id)
);

CREATE INDEX idx_rt_tenant_student_date ON edu_review_task(tenant_id, student_id, review_date);

CREATE INDEX idx_rt_tenant_knowledge ON edu_review_task(tenant_id, knowledge_id);

CREATE TABLE edu_study_plan(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY  NOT NULL,
    student_id BIGINT NOT NULL,
    target_knowledge_id BIGINT DEFAULT NULL,
    name CHARACTER VARYING(200) DEFAULT NULL,
    start_date DATE DEFAULT NULL,
    end_date DATE DEFAULT NULL,
    status SMALLINT DEFAULT 0,
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    tenant_id BIGINT NOT NULL,
    create_by CHARACTER VARYING(64) DEFAULT NULL,
    update_by CHARACTER VARYING(64) DEFAULT NULL,
    del_flag SMALLINT DEFAULT 0,
    CONSTRAINT pk_edu_study_plan PRIMARY KEY(id)
);

CREATE INDEX idx_sp_tenant_student ON edu_study_plan(tenant_id, student_id);

CREATE TABLE edu_study_plan_item(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY  NOT NULL,
    plan_id BIGINT NOT NULL,
    knowledge_id BIGINT NOT NULL,
    plan_date DATE NOT NULL,
    order_no INTEGER NOT NULL,
    status SMALLINT DEFAULT 0,
    completed_at TIMESTAMP,
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    tenant_id BIGINT NOT NULL,
    create_by CHARACTER VARYING(64) DEFAULT NULL,
    update_by CHARACTER VARYING(64) DEFAULT NULL,
    del_flag SMALLINT DEFAULT 0,
    CONSTRAINT pk_edu_study_plan_item PRIMARY KEY(id)
);

CREATE INDEX idx_spi_tenant_plan ON edu_study_plan_item(tenant_id, plan_id);

CREATE INDEX idx_spi_tenant_knowledge ON edu_study_plan_item(tenant_id, knowledge_id);

CREATE TABLE edu_wrong_question(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY  NOT NULL,
    student_id BIGINT NOT NULL,
    question_id BIGINT NOT NULL,
    knowledge_id BIGINT DEFAULT NULL,
    student_answer CHARACTER VARYING DEFAULT NULL,
    correct_times INTEGER DEFAULT 0,
    created_at TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    tenant_id BIGINT NOT NULL,
    status SMALLINT DEFAULT 1,
    del_flag SMALLINT DEFAULT 0,
    create_by CHARACTER VARYING(64),
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_by CHARACTER VARYING(64),
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_edu_wrong_question PRIMARY KEY(id)
);

CREATE INDEX idx_wq_tenant_student ON edu_wrong_question(tenant_id, student_id);

CREATE INDEX idx_wq_tenant_question ON edu_wrong_question(tenant_id, question_id);

CREATE TABLE edu_learning_state(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY  NOT NULL,
    student_id BIGINT NOT NULL,
    knowledge_id BIGINT NOT NULL,
    state CHARACTER VARYING(20) DEFAULT 'NOT_STARTED' NOT NULL,
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    tenant_id BIGINT NOT NULL,
    status SMALLINT DEFAULT 1,
    del_flag SMALLINT DEFAULT 0,
    create_by CHARACTER VARYING(64),
    update_by CHARACTER VARYING(64),
    CONSTRAINT pk_edu_learning_state PRIMARY KEY(id),
    CONSTRAINT uk_learning_state_tenant UNIQUE  (tenant_id, student_id, knowledge_id)
);

CREATE TABLE edu_achievement(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1)  NOT NULL,
    student_id BIGINT NOT NULL,
    code CHARACTER VARYING(50) NOT NULL,
    name CHARACTER VARYING(100) NOT NULL,
    description CHARACTER VARYING(500) DEFAULT NULL,
    icon CHARACTER VARYING(200) DEFAULT NULL,
    earned_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    tenant_id BIGINT NOT NULL,
    status SMALLINT DEFAULT 1,
    del_flag SMALLINT DEFAULT 0,
    create_by CHARACTER VARYING(64),
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_by CHARACTER VARYING(64),
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_edu_achievement PRIMARY KEY(id),
    CONSTRAINT uk_achievement_tenant UNIQUE  (tenant_id, student_id, code)
);

CREATE INDEX idx_edu_ability_tenant ON edu_ability(tenant_id);
CREATE INDEX idx_edu_textbook_tenant ON edu_textbook(tenant_id);
CREATE INDEX idx_edu_knowledge_textbook_tenant ON edu_knowledge_textbook(tenant_id);
CREATE INDEX idx_edu_teacher_tenant ON edu_teacher(tenant_id);
CREATE INDEX idx_edu_subject_tenant ON edu_subject(tenant_id);
CREATE INDEX idx_edu_course_knowledge_tenant ON edu_course_knowledge(tenant_id);
CREATE INDEX idx_edu_resource_knowledge_tenant ON edu_resource_knowledge(tenant_id);
CREATE INDEX idx_edu_question_knowledge_tenant ON edu_question_knowledge(tenant_id);
CREATE INDEX idx_edu_exam_section_tenant ON edu_exam_section(tenant_id);
CREATE INDEX idx_edu_exam_question_tenant ON edu_exam_question(tenant_id);
CREATE INDEX idx_edu_learning_state_tenant ON edu_learning_state(tenant_id);
CREATE INDEX idx_edu_achievement_tenant ON edu_achievement(tenant_id);

-- Source: modules/domains/knowledge/shiyu-knowledge-implementation/src/main/resources/db/baseline/h2/schema/knowledge/09_vector.sql
-- Final H2 schema baseline. Generated from the validated schema; do not add migrations here.

CREATE TABLE vector_knowledge_chunk(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY  NOT NULL,
    document_id BIGINT NOT NULL,
    content CHARACTER VARYING NOT NULL,
    embedding CHARACTER VARYING DEFAULT NULL,
    metadata CHARACTER VARYING DEFAULT NULL,
    chunk_index INTEGER DEFAULT 0,
    tenant_id BIGINT NOT NULL,
    create_by CHARACTER VARYING(64) DEFAULT NULL,
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_by CHARACTER VARYING(64) DEFAULT NULL,
    update_time TIMESTAMP DEFAULT NULL,
    status SMALLINT DEFAULT 1,
    del_flag SMALLINT DEFAULT 0,
    space_id BIGINT DEFAULT NULL,
    version_id BIGINT DEFAULT NULL,
    embedding_binary BINARY LARGE OBJECT DEFAULT NULL,
    embedding_model CHARACTER VARYING(100) DEFAULT NULL,
    embedding_dimension INTEGER DEFAULT NULL,
    page_number INTEGER DEFAULT NULL,
    section_path CHARACTER VARYING(1000) DEFAULT NULL,
    start_offset INTEGER DEFAULT NULL,
    end_offset INTEGER DEFAULT NULL,
    token_count INTEGER DEFAULT NULL,
    CONSTRAINT pk_vector_knowledge_chunk PRIMARY KEY(id)
);

CREATE INDEX idx_kc_document ON vector_knowledge_chunk(document_id);

CREATE INDEX idx_knowledge_chunk_space ON vector_knowledge_chunk(tenant_id, space_id, document_id);

-- Source: modules/domains/governance/shiyu-governance-implementation/src/main/resources/db/baseline/h2/schema/governance/10_observation.sql
-- Final H2 schema baseline. Generated from the validated schema; do not add migrations here.

CREATE TABLE observation_audit_log(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1)  NOT NULL,
    tenant_id BIGINT NOT NULL,
    user_id BIGINT DEFAULT NULL,
    action CHARACTER VARYING(64) NOT NULL,
    target_type CHARACTER VARYING(64) DEFAULT NULL,
    target_id CHARACTER VARYING(128) DEFAULT NULL,
    detail CHARACTER VARYING DEFAULT NULL,
    ip CHARACTER VARYING(64) DEFAULT NULL,
    result CHARACTER VARYING(16) DEFAULT 'SUCCESS',
    error_msg CHARACTER VARYING(500) DEFAULT NULL,
    duration_ms BIGINT DEFAULT 0,
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_observation_audit_log PRIMARY KEY(id)
);

CREATE INDEX idx_tenant_id ON observation_audit_log(tenant_id);

CREATE INDEX idx_user_id ON observation_audit_log(user_id);

CREATE INDEX idx_action ON observation_audit_log(action);

CREATE INDEX idx_target_type ON observation_audit_log(target_type);

CREATE INDEX idx_create_time ON observation_audit_log(create_time);

CREATE TABLE observation_execution_timeline(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1)  NOT NULL,
    tenant_id BIGINT NOT NULL,
    execution_id CHARACTER VARYING(128) NOT NULL,
    agent_id CHARACTER VARYING(128) DEFAULT NULL,
    node_id CHARACTER VARYING(128) DEFAULT NULL,
    node_type CHARACTER VARYING(64) DEFAULT NULL,
    event_type CHARACTER VARYING(32) NOT NULL,
    payload CHARACTER VARYING DEFAULT NULL,
    duration_ms BIGINT DEFAULT 0,
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_observation_execution_timeline PRIMARY KEY(id)
);

CREATE INDEX idx_timeline_tenant_execution_id ON observation_execution_timeline(tenant_id, execution_id);

CREATE INDEX idx_timeline_agent_id ON observation_execution_timeline(agent_id);

CREATE INDEX idx_timeline_event_type ON observation_execution_timeline(event_type);

CREATE INDEX idx_timeline_create_time ON observation_execution_timeline(create_time);

-- Source: modules/domains/conversation/shiyu-conversation-implementation/src/main/resources/db/baseline/h2/schema/conversation/11_conversation.sql
-- Platform conversation source of truth. Messages are never duplicated into memory tables.
CREATE TABLE IF NOT EXISTS chat_conversation (
    id CHARACTER VARYING(64) NOT NULL,
    tenant_id BIGINT NOT NULL,
    owner_user_id BIGINT NOT NULL,
    scene_type CHARACTER VARYING(64) NOT NULL,
    title CHARACTER VARYING(255),
    status CHARACTER VARYING(16) NOT NULL,
    parent_conversation_id CHARACTER VARYING(64),
    branch_from_message_id CHARACTER VARYING(64),
    active_leaf_message_id CHARACTER VARYING(64),
    rolling_summary TEXT,
    platform CHARACTER VARYING(64),
    model CHARACTER VARYING(128),
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT pk_chat_conversation PRIMARY KEY (id)
);
CREATE INDEX IF NOT EXISTS idx_chat_conv_owner ON chat_conversation(tenant_id, owner_user_id, status);

CREATE TABLE IF NOT EXISTS chat_message (
    id CHARACTER VARYING(64) NOT NULL,
    tenant_id BIGINT NOT NULL,
    conversation_id CHARACTER VARYING(64) NOT NULL,
    parent_message_id CHARACTER VARYING(64),
    source_message_id CHARACTER VARYING(64),
    role CHARACTER VARYING(16) NOT NULL,
    content TEXT NOT NULL,
    content_parts TEXT,
    tool_call TEXT,
    status CHARACTER VARYING(16) NOT NULL,
    sequence INTEGER NOT NULL,
    generation_id CHARACTER VARYING(64),
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT pk_chat_message PRIMARY KEY (id)
);
CREATE INDEX IF NOT EXISTS idx_chat_message_conv_seq ON chat_message(tenant_id, conversation_id, sequence);

CREATE TABLE IF NOT EXISTS chat_generation_run (
    id CHARACTER VARYING(64) NOT NULL,
    tenant_id BIGINT NOT NULL,
    conversation_id CHARACTER VARYING(64) NOT NULL,
    input_message_id CHARACTER VARYING(64),
    assistant_message_id CHARACTER VARYING(64),
    runtime_run_id CHARACTER VARYING(64),
    speaker_id CHARACTER VARYING(128),
    platform CHARACTER VARYING(64),
    model CHARACTER VARYING(128),
    status CHARACTER VARYING(24) NOT NULL,
    prompt_tokens BIGINT DEFAULT 0,
    completion_tokens BIGINT DEFAULT 0,
    latency_ms BIGINT DEFAULT 0,
    error_code CHARACTER VARYING(128),
    last_event_sequence INTEGER DEFAULT -1,
    cancel_requested BOOLEAN NOT NULL DEFAULT FALSE,
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT pk_chat_generation_run PRIMARY KEY (id)
);
CREATE INDEX IF NOT EXISTS idx_chat_generation_run_conv ON chat_generation_run(tenant_id, conversation_id, created_at);

-- Database-level admission reservation.  It closes the check-then-insert
-- race for retries on the same active user message; the row is released when
-- the GenerationRun reaches any terminal state.
CREATE TABLE IF NOT EXISTS chat_generation_active (
    tenant_id BIGINT NOT NULL,
    conversation_id CHARACTER VARYING(64) NOT NULL,
    input_message_id CHARACTER VARYING(64) NOT NULL,
    generation_id CHARACTER VARYING(64) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT pk_chat_generation_active PRIMARY KEY (tenant_id, conversation_id, input_message_id),
    CONSTRAINT uk_chat_generation_active_run UNIQUE (generation_id)
);

-- Generation events are a typed projection of AI_RUN_EVENT. Do not create a
-- second physical stream.

CREATE TABLE IF NOT EXISTS chat_idempotency_key (
    tenant_id BIGINT NOT NULL,
    owner_user_id BIGINT NOT NULL,
    key_value CHARACTER VARYING(128) NOT NULL,
    operation CHARACTER VARYING(64) NOT NULL,
    resource_id CHARACTER VARYING(64) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT pk_chat_idempotency_key PRIMARY KEY (tenant_id, owner_user_id, key_value, operation)
);

CREATE INDEX IF NOT EXISTS idx_chat_generation_active_tenant ON chat_generation_active(tenant_id);
CREATE INDEX IF NOT EXISTS idx_chat_idempotency_key_tenant ON chat_idempotency_key(tenant_id);

-- Conversation-owned product assets: characters, personas, lorebooks, prompts and group chats.
CREATE TABLE IF NOT EXISTS chat_character_asset (
    id CHARACTER VARYING(64) NOT NULL,
    tenant_id BIGINT NOT NULL,
    owner_user_id BIGINT NOT NULL,
    card_json TEXT NOT NULL,
    png_data BYTEA,
    visibility CHARACTER VARYING(16) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT pk_chat_character_asset PRIMARY KEY (id)
);
CREATE INDEX IF NOT EXISTS idx_chat_character_owner ON chat_character_asset(tenant_id, owner_user_id);
CREATE TABLE IF NOT EXISTS chat_persona_asset (
    id CHARACTER VARYING(64) NOT NULL,
    tenant_id BIGINT NOT NULL,
    owner_user_id BIGINT NOT NULL,
    persona_json TEXT NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT pk_chat_persona_asset PRIMARY KEY (id)
);
CREATE INDEX IF NOT EXISTS idx_chat_persona_owner ON chat_persona_asset(tenant_id, owner_user_id);
CREATE TABLE IF NOT EXISTS chat_lorebook_asset (
    id CHARACTER VARYING(64) NOT NULL,
    tenant_id BIGINT NOT NULL,
    owner_user_id BIGINT NOT NULL,
    entry_json TEXT NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT pk_chat_lorebook_asset PRIMARY KEY (id)
);
CREATE INDEX IF NOT EXISTS idx_chat_lorebook_owner ON chat_lorebook_asset(tenant_id, owner_user_id);
CREATE TABLE IF NOT EXISTS chat_prompt_template (
    id CHARACTER VARYING(64) NOT NULL,
    tenant_id BIGINT NOT NULL,
    owner_user_id BIGINT NOT NULL,
    template_id CHARACTER VARYING(64) NOT NULL,
    version INTEGER NOT NULL,
    status CHARACTER VARYING(16) NOT NULL,
    body TEXT NOT NULL,
    variable_schema TEXT,
    test_cases TEXT,
    created_at TIMESTAMP NOT NULL,
    published_at TIMESTAMP,
    CONSTRAINT pk_chat_prompt_template PRIMARY KEY (id),
    CONSTRAINT uk_chat_prompt_version UNIQUE (tenant_id, owner_user_id, template_id, version)
);
CREATE INDEX IF NOT EXISTS idx_chat_prompt_owner ON chat_prompt_template(tenant_id, owner_user_id, template_id);
CREATE TABLE IF NOT EXISTS chat_group_chat (
    id CHARACTER VARYING(64) NOT NULL,
    tenant_id BIGINT NOT NULL,
    owner_user_id BIGINT NOT NULL,
    name CHARACTER VARYING(255) NOT NULL,
    participants_json TEXT NOT NULL,
    speaker_policy CHARACTER VARYING(32) NOT NULL,
    max_turns INTEGER NOT NULL,
    token_budget INTEGER NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT pk_chat_group_chat PRIMARY KEY (id)
);
CREATE INDEX IF NOT EXISTS idx_chat_group_owner ON chat_group_chat(tenant_id, owner_user_id);

-- Source: modules/domains/memory/shiyu-memory-implementation/src/main/resources/db/baseline/h2/schema/memory/12_memory_magma.sql
-- MAGMA-based platform memory. One event participates in multiple relation graphs.
CREATE TABLE IF NOT EXISTS memory_event (
    id CHARACTER VARYING(64) NOT NULL,
    tenant_id BIGINT NOT NULL,
    namespace CHARACTER VARYING(64) NOT NULL,
    subject_type CHARACTER VARYING(64) NOT NULL,
    subject_id CHARACTER VARYING(128) NOT NULL,
    event_type CHARACTER VARYING(64) NOT NULL,
    content TEXT NOT NULL,
    occurred_at TIMESTAMP NOT NULL,
    source_type CHARACTER VARYING(64),
    source_id CHARACTER VARYING(128),
    attributes TEXT,
    confidence DOUBLE NOT NULL,
    importance DOUBLE NOT NULL,
    status CHARACTER VARYING(16) NOT NULL,
    confirmation_policy CHARACTER VARYING(16) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT pk_memory_event PRIMARY KEY (id)
);
CREATE INDEX IF NOT EXISTS idx_memory_event_subject ON memory_event(tenant_id, namespace, subject_type, subject_id, occurred_at);
CREATE INDEX IF NOT EXISTS idx_memory_event_status ON memory_event(tenant_id, status);

CREATE TABLE IF NOT EXISTS memory_entity (
    id CHARACTER VARYING(64) NOT NULL,
    tenant_id BIGINT NOT NULL,
    entity_type CHARACTER VARYING(64) NOT NULL,
    external_ref CHARACTER VARYING(255) NOT NULL,
    display_name CHARACTER VARYING(255),
    normalized_name CHARACTER VARYING(255),
    attributes TEXT,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT pk_memory_entity PRIMARY KEY (id),
    CONSTRAINT uk_memory_entity_ref UNIQUE (tenant_id, entity_type, external_ref)
);

CREATE TABLE IF NOT EXISTS memory_edge (
    id CHARACTER VARYING(64) NOT NULL,
    tenant_id BIGINT NOT NULL,
    source_node_id CHARACTER VARYING(64) NOT NULL,
    target_node_id CHARACTER VARYING(64) NOT NULL,
    graph_type CHARACTER VARYING(16) NOT NULL,
    relation_type CHARACTER VARYING(64) NOT NULL,
    directed BOOLEAN NOT NULL,
    weight DOUBLE NOT NULL,
    confidence DOUBLE NOT NULL,
    origin CHARACTER VARYING(16) NOT NULL,
    evidence_source CHARACTER VARYING(255),
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT pk_memory_edge PRIMARY KEY (id)
);
CREATE INDEX IF NOT EXISTS idx_memory_edge_source ON memory_edge(tenant_id, source_node_id, graph_type, active);
CREATE INDEX IF NOT EXISTS idx_memory_edge_target ON memory_edge(tenant_id, target_node_id, graph_type, active);

CREATE TABLE IF NOT EXISTS memory_consolidation_job (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    tenant_id BIGINT NOT NULL,
    event_id CHARACTER VARYING(64) NOT NULL,
    status CHARACTER VARYING(16) NOT NULL DEFAULT 'PENDING',
    attempts INTEGER NOT NULL DEFAULT 0,
    available_at TIMESTAMP NOT NULL,
    leased_until TIMESTAMP,
    last_error CHARACTER VARYING(2000),
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT pk_memory_consolidation_job PRIMARY KEY (id)
);
CREATE INDEX IF NOT EXISTS idx_memory_job_status ON memory_consolidation_job(status, available_at);

CREATE TABLE IF NOT EXISTS memory_retrieval_trace (
    id CHARACTER VARYING(64) NOT NULL,
    tenant_id BIGINT NOT NULL,
    namespace CHARACTER VARYING(64) NOT NULL,
    query_text TEXT NOT NULL,
    anchor_event_ids TEXT,
    graph_weights_json TEXT,
    relation_paths_json TEXT,
    filtered_event_ids TEXT,
    result_event_ids TEXT,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT pk_memory_retrieval_trace PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_memory_entity_tenant ON memory_entity(tenant_id);
CREATE INDEX IF NOT EXISTS idx_memory_consolidation_job_tenant ON memory_consolidation_job(tenant_id);
CREATE INDEX IF NOT EXISTS idx_memory_trace_tenant ON memory_retrieval_trace(tenant_id, created_at);

-- Source: modules/domains/tooling/shiyu-tooling-implementation/src/main/resources/db/baseline/h2/schema/tooling/15_plugin_market.sql
CREATE TABLE IF NOT EXISTS plugin_market_entry (
    id CHARACTER VARYING(128) NOT NULL,
    version CHARACTER VARYING(64) NOT NULL,
    source TEXT,
    manifest TEXT NOT NULL,
    signature TEXT,
    publisher_key TEXT,
    permissions_json TEXT NOT NULL,
    checksum CHARACTER VARYING(128),
    update_policy CHARACTER VARYING(32) NOT NULL,
    published_at TIMESTAMP NOT NULL,
    enabled BOOLEAN NOT NULL,
    CONSTRAINT pk_plugin_market_entry PRIMARY KEY (id, version)
);
CREATE INDEX IF NOT EXISTS idx_plugin_market_id ON plugin_market_entry(id);

-- Source: modules/domains/agent/shiyu-agent-implementation/src/main/resources/db/baseline/h2/schema/agent/16_ai_runtime.sql
CREATE TABLE IF NOT EXISTS ai_app (
    id CHARACTER VARYING(64) NOT NULL,
    tenant_id BIGINT NOT NULL,
    owner_user_id BIGINT NOT NULL,
    name CHARACTER VARYING(255) NOT NULL,
    description TEXT,
    status CHARACTER VARYING(24) NOT NULL,
    published_version_id CHARACTER VARYING(64),
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT pk_ai_app PRIMARY KEY (id)
);
CREATE INDEX IF NOT EXISTS idx_ai_app_owner ON ai_app(tenant_id, owner_user_id, status);

CREATE TABLE IF NOT EXISTS ai_app_version (
    id CHARACTER VARYING(64) NOT NULL,
    app_id CHARACTER VARYING(64) NOT NULL,
    tenant_id BIGINT NOT NULL,
    version CHARACTER VARYING(64) NOT NULL,
    config_json TEXT NOT NULL,
    status CHARACTER VARYING(24) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    published_at TIMESTAMP,
    CONSTRAINT pk_ai_app_version PRIMARY KEY (id),
    CONSTRAINT uk_ai_app_version UNIQUE (app_id, version)
);
CREATE INDEX IF NOT EXISTS idx_ai_app_version_app ON ai_app_version(tenant_id, app_id, status);

CREATE TABLE IF NOT EXISTS ai_run (
    id CHARACTER VARYING(64) NOT NULL,
    tenant_id BIGINT NOT NULL,
    owner_user_id BIGINT NOT NULL,
    app_id CHARACTER VARYING(64),
    app_version_id CHARACTER VARYING(64),
    source_type CHARACTER VARYING(32) NOT NULL,
    source_id CHARACTER VARYING(128) NOT NULL,
    parent_run_id CHARACTER VARYING(64),
    trace_id CHARACTER VARYING(128) NOT NULL,
    conversation_id CHARACTER VARYING(64),
    generation_id CHARACTER VARYING(64),
    execution_id CHARACTER VARYING(64),
    model CHARACTER VARYING(128),
    prompt_hash CHARACTER VARYING(128),
    status CHARACTER VARYING(24) NOT NULL,
    prompt_tokens BIGINT NOT NULL DEFAULT 0,
    completion_tokens BIGINT NOT NULL DEFAULT 0,
    estimated_usage BOOLEAN NOT NULL DEFAULT TRUE,
    cost_snapshot TEXT,
    created_at TIMESTAMP NOT NULL,
    completed_at TIMESTAMP,
    error_code CHARACTER VARYING(128),
    last_event_seq BIGINT NOT NULL DEFAULT 0,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT pk_ai_run PRIMARY KEY (id)
);
CREATE INDEX IF NOT EXISTS idx_ai_run_owner ON ai_run(tenant_id, owner_user_id, created_at);
CREATE INDEX IF NOT EXISTS idx_ai_run_trace ON ai_run(tenant_id, trace_id);

CREATE TABLE IF NOT EXISTS ai_run_event (
    run_id CHARACTER VARYING(64) NOT NULL,
    tenant_id BIGINT NOT NULL,
    seq BIGINT NOT NULL,
    type CHARACTER VARYING(48) NOT NULL,
    schema_version INTEGER NOT NULL DEFAULT 1,
    turn_id CHARACTER VARYING(64),
    step_id CHARACTER VARYING(64),
    parent_event_seq BIGINT,
    conversation_id CHARACTER VARYING(64),
    generation_id CHARACTER VARYING(64),
    execution_id CHARACTER VARYING(64),
    app_id CHARACTER VARYING(64),
    app_version_id CHARACTER VARYING(64),
    provider_request_id CHARACTER VARYING(255),
    trace_id CHARACTER VARYING(128),
    payload TEXT NOT NULL,
    redacted BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT pk_ai_run_event PRIMARY KEY (run_id, seq)
);
CREATE TABLE IF NOT EXISTS ai_tool_approval (
    id CHARACTER VARYING(64) NOT NULL,
    run_id CHARACTER VARYING(64) NOT NULL,
    tenant_id BIGINT NOT NULL,
    owner_user_id BIGINT NOT NULL,
    tool_name CHARACTER VARYING(255) NOT NULL,
    arguments_redacted TEXT,
    status CHARACTER VARYING(24) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    decided_at TIMESTAMP,
    expires_at TIMESTAMP,
    CONSTRAINT pk_ai_tool_approval PRIMARY KEY (id)
);
CREATE INDEX IF NOT EXISTS idx_ai_tool_approval_run ON ai_tool_approval(tenant_id, run_id, status);

CREATE INDEX IF NOT EXISTS idx_ai_run_event_tenant ON ai_run_event(tenant_id, run_id, seq);
