### ==========================================
### 全局变量
### 通过 @baseUrl 和 @authToken 复用
### 先执行 Login 获取 token，然后手动设置 @authToken
### ==========================================

@baseUrl = http://localhost:9000
@authToken = 
