-- Final knowledge seed baseline. Executed once on an empty H2 database.

INSERT INTO "PUBLIC"."KNOWLEDGE_DIFFICULTY_SCALE" VALUES(1, 'STANDARD_5', '标准五级难度', '适用于通用知识体系的五级难度量表', 5, 1, 1, 0, 'system', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP);
INSERT INTO "PUBLIC"."KNOWLEDGE_DIFFICULTY_SCALE_LEVEL" VALUES(1, 1, 1, '入门', '基础知识与概念理解', 1, 1, 0, 'system', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP);
INSERT INTO "PUBLIC"."KNOWLEDGE_DIFFICULTY_SCALE_LEVEL" VALUES(2, 1, 2, '基础', '基础应用与简单推理', 1, 1, 0, 'system', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP);
INSERT INTO "PUBLIC"."KNOWLEDGE_DIFFICULTY_SCALE_LEVEL" VALUES(3, 1, 3, '中等', '综合运用与中等推理', 1, 1, 0, 'system', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP);
INSERT INTO "PUBLIC"."KNOWLEDGE_DIFFICULTY_SCALE_LEVEL" VALUES(4, 1, 4, '较难', '复杂问题分析与推理', 1, 1, 0, 'system', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP);
INSERT INTO "PUBLIC"."KNOWLEDGE_DIFFICULTY_SCALE_LEVEL" VALUES(5, 1, 5, '挑战', '高难度综合与创新', 1, 1, 0, 'system', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP);
