-- Governance-owned v4 schema. No cross-domain foreign keys or joins.

CREATE CACHED TABLE "PUBLIC"."GOVERNANCE_USAGE_RECORD" (
    "ID" CHARACTER VARYING(64) NOT NULL,
    "TENANT_ID" BIGINT NOT NULL,
    "USER_ID" BIGINT NOT NULL,
    "CORRELATION_ID" CHARACTER VARYING(128) NOT NULL,
    "SOURCE_TYPE" CHARACTER VARYING(64) NOT NULL,
    "SOURCE_ID" CHARACTER VARYING(128) NOT NULL,
    "INPUT_TOKENS" BIGINT DEFAULT 0 NOT NULL,
    "OUTPUT_TOKENS" BIGINT DEFAULT 0 NOT NULL,
    "COST" DECIMAL(20, 8) DEFAULT 0 NOT NULL,
    "OCCURRED_AT" TIMESTAMP NOT NULL,
    "USAGE_TYPE" CHARACTER VARYING(32) DEFAULT 'METERED' NOT NULL,
    "LATENCY_MS" BIGINT,
    "SESSION_ID" CHARACTER VARYING(128),
    "EXT_INFO" CHARACTER LARGE OBJECT,
    "CREATE_TIME" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT "PK_GOVERNANCE_USAGE_RECORD" PRIMARY KEY ("ID"),
    CONSTRAINT "UK_GOVERNANCE_USAGE_SOURCE" UNIQUE ("TENANT_ID", "SOURCE_TYPE", "SOURCE_ID"),
    CONSTRAINT "CK_GOVERNANCE_USAGE_INPUT" CHECK ("INPUT_TOKENS" >= 0),
    CONSTRAINT "CK_GOVERNANCE_USAGE_OUTPUT" CHECK ("OUTPUT_TOKENS" >= 0),
    CONSTRAINT "CK_GOVERNANCE_USAGE_COST" CHECK ("COST" >= 0)
);

CREATE INDEX "PUBLIC"."IDX_GOVERNANCE_USAGE_TENANT_TIME"
    ON "PUBLIC"."GOVERNANCE_USAGE_RECORD" ("TENANT_ID", "OCCURRED_AT");

CREATE INDEX "PUBLIC"."IDX_GOVERNANCE_USAGE_TENANT_USER_TIME"
    ON "PUBLIC"."GOVERNANCE_USAGE_RECORD" ("TENANT_ID", "USER_ID", "OCCURRED_AT");
