package com.shiyu.ai.architecture;

import com.tngtech.archunit.core.importer.ImportOption;
import com.tngtech.archunit.core.importer.Location;
import com.tngtech.archunit.junit.AnalyzeClasses;
import com.tngtech.archunit.junit.ArchTest;
import com.tngtech.archunit.lang.ArchRule;

import static com.tngtech.archunit.library.dependencies.SlicesRuleDefinition.slices;
import static com.tngtech.archunit.lang.syntax.ArchRuleDefinition.noClasses;

@AnalyzeClasses(packages = "com.shiyu.ai", importOptions = {
        ImportOption.DoNotIncludeTests.class,
        ArchitectureRulesTest.DoNotIncludeLegacyPlatformBuilds.class
})
class ArchitectureRulesTest {

    /**
     * The old platform modules are no longer part of the Maven reactor. This
     * keeps locally generated bytecode from a pre-migration checkout out of
     * the classpath scan; a clean checkout has no matching locations.
     */
    public static final class DoNotIncludeLegacyPlatformBuilds implements ImportOption {
        @Override
        public boolean includes(Location location) {
            return !location.asURI().toString().replace('\\', '/').contains("/platform/");
        }
    }

    @ArchTest
    static final ArchRule IMPLEMENTATIONS_ARE_NOT_COUPLED = slices()
            .matching("com.shiyu.ai.(*)..implementation..")
            .should().notDependOnEachOther()
            .because("bounded contexts may depend on another context only through its contract");

    @ArchTest
    static final ArchRule CONTRACTS_ARE_FRAMEWORK_FREE = noClasses()
            .that().resideInAPackage("com.shiyu.ai..contract..")
            .should().dependOnClassesThat().resideInAnyPackage(
                    "org.springframework..",
                    "jakarta.persistence..",
                    "com.baomidou..",
                    "org.apache.ibatis.."
            )
            .because("contracts must remain portable and framework free");

    @ArchTest
    static final ArchRule DOMAIN_AND_APPLICATION_LAYERS_DO_NOT_READ_THREAD_CONTEXT = noClasses()
            .that().resideInAnyPackage(
                    "com.shiyu.ai..implementation.application..",
                    "com.shiyu.ai..implementation.domain.."
            )
            .should().dependOnClassesThat()
            .haveFullyQualifiedName("com.shiyu.ai.common.core.domain.UserContextHolder")
            .allowEmptyShould(true)
            .because("ActorContext must enter through an explicit application boundary");

    @ArchTest
    static final ArchRule DOMAIN_AND_APPLICATION_LAYERS_DO_NOT_READ_TENANT_SCOPE = noClasses()
            .that().resideInAnyPackage(
                    "com.shiyu.ai..implementation.application..",
                    "com.shiyu.ai..implementation.domain.."
            )
            .should().dependOnClassesThat()
            .haveFullyQualifiedName("com.shiyu.ai.kernel.context.TenantScope")
            .allowEmptyShould(true)
            .because("TenantScope is a transport/persistence adapter concern; commands carry TenantId explicitly");

    @ArchTest
    static final ArchRule LEGACY_KNOWLEDGE_DOMAIN_DOES_NOT_READ_THREAD_CONTEXT = noClasses()
            .that().resideInAPackage("com.shiyu.ai.knowledge..")
            .should().dependOnClassesThat()
            .haveFullyQualifiedName("com.shiyu.ai.common.core.domain.UserContextHolder")
            .because("knowledge application services must receive ActorContext explicitly");

    @ArchTest
    static final ArchRule WEB_DOMAIN_ADAPTERS_DO_NOT_READ_THREAD_CONTEXT = noClasses()
            .that().resideInAnyPackage(
                    "com.shiyu.ai.web.agent..",
                    "com.shiyu.ai.web.chat..",
                    "com.shiyu.ai.web.common..",
                    "com.shiyu.ai.web.conversation..",
                    "com.shiyu.ai.web.education..",
                    "com.shiyu.ai.web.evaluation..",
                    "com.shiyu.ai.web.knowledge..",
                    "com.shiyu.ai.web.memory..",
                    "com.shiyu.ai.web.model..",
                    "com.shiyu.ai.web.openai..",
                    "com.shiyu.ai.web.prompt..",
                    "com.shiyu.ai.web.runtime..",
                    "com.shiyu.ai.web.usage.."
            )
            .should().dependOnClassesThat()
            .haveFullyQualifiedName("com.shiyu.ai.common.core.domain.UserContextHolder")
            .because("only the HTTP authentication adapter may translate thread context into ActorContext");

    @ArchTest
    static final ArchRule MIGRATED_IAM_SERVICES_DO_NOT_READ_THREAD_CONTEXT = noClasses()
            .that().haveFullyQualifiedName("com.shiyu.ai.auth.service.impl.UserServiceImpl")
            .or().haveFullyQualifiedName("com.shiyu.ai.auth.service.impl.AuthCodeServiceImpl")
            .or().haveFullyQualifiedName("com.shiyu.ai.auth.service.impl.RoleServiceImpl")
            .or().haveFullyQualifiedName("com.shiyu.ai.auth.service.impl.TenantServiceImpl")
            .or().haveFullyQualifiedName("com.shiyu.ai.auth.service.impl.MenuServiceImpl")
            .or().haveFullyQualifiedName("com.shiyu.ai.auth.service.impl.DictServiceImpl")
            .or().haveFullyQualifiedName("com.shiyu.ai.auth.service.impl.AuthServiceImpl")
            .should().dependOnClassesThat()
            .haveFullyQualifiedName("com.shiyu.ai.common.core.domain.UserContextHolder")
            .because("migrated IAM application services must receive ActorContext explicitly");

    @ArchTest
    static final ArchRule IAM_REPOSITORIES_DO_NOT_READ_THREAD_CONTEXT = noClasses()
            .that().resideInAPackage("com.shiyu.ai.auth.persistence.repository..")
            .should().dependOnClassesThat()
            .haveFullyQualifiedName("com.shiyu.ai.common.core.domain.UserContextHolder")
            .because("IAM repositories must receive tenant scope explicitly; thread context is an HTTP-edge concern");

    @ArchTest
    static final ArchRule MYBATIS_SUPPORT_DOES_NOT_READ_THREAD_CONTEXT = noClasses()
            .that().resideInAPackage("com.shiyu.ai.common.mybatis..")
            .should().dependOnClassesThat()
            .haveFullyQualifiedName("com.shiyu.ai.common.core.domain.UserContextHolder")
            .because("persistence listeners must not infer tenant or actor identity from an HTTP thread");

    @ArchTest
    static final ArchRule COMMON_WEB_SUPPORT_DOES_NOT_READ_THREAD_CONTEXT = noClasses()
            .that().resideInAPackage("com.shiyu.ai.common.web..")
            .and().doNotHaveFullyQualifiedName("com.shiyu.ai.common.web.auth.ActorContextHttpAdapter")
            .should().dependOnClassesThat()
            .haveFullyQualifiedName("com.shiyu.ai.common.core.domain.UserContextHolder")
            .because("shared web logging and filters must use request attributes, not authentication thread state");

    @ArchTest
    static final ArchRule IAM_ADAPTERS_DO_NOT_READ_THREAD_CONTEXT = noClasses()
            .that().resideInAnyPackage("com.shiyu.ai.auth..")
            .should().dependOnClassesThat()
            .haveFullyQualifiedName("com.shiyu.ai.common.core.domain.UserContextHolder")
            .because("IAM implementations must remain independent of the HTTP authentication thread context");

    @ArchTest
    static final ArchRule MYBATIS_ADAPTERS_DO_NOT_READ_HTTP_AUTH_CONTEXT = noClasses()
            .that().resideInAnyPackage("com.shiyu.ai.common.mybatis..")
            .should().dependOnClassesThat()
            .haveFullyQualifiedName("com.shiyu.ai.common.core.domain.UserContextHolder")
            .because("persistence adapters must receive tenant scope through an explicit technical boundary");
}
