package com.shiyu.ai.bootstrap;

import lombok.Data;
import org.springframework.boot.context.properties.ConfigurationProperties;
import org.springframework.stereotype.Component;

/** Limits the on-disk history generated by Log4j2 rolling appenders. */
@Data
@Component
@ConfigurationProperties(prefix = "shiyu.retention.logs")
public class LogRetentionProperties {

    private boolean enabled = true;
    private int maxAgeDays = 30;
    private long maxTotalBytes = 2L * 1024 * 1024 * 1024;
}
