-- 权限契约对齐；只补齐缺失记录，不覆盖现有权限或授权的启停状态。
INSERT INTO AUTH_AUTH_CODE (ID, CODE, NAME, STATUS, DEL_FLAG, CREATE_BY, UPDATE_BY)
SELECT (SELECT COALESCE(MAX(ID), 0) + 1 FROM AUTH_AUTH_CODE),
       'model:admin', '管理模型网关', 1, 0, 'system', 'system'
WHERE NOT EXISTS (SELECT 1 FROM AUTH_AUTH_CODE WHERE CODE = 'model:admin');

INSERT INTO AUTH_AUTH_CODE (ID, CODE, NAME, STATUS, DEL_FLAG, CREATE_BY, UPDATE_BY)
SELECT (SELECT COALESCE(MAX(ID), 0) + 1 FROM AUTH_AUTH_CODE),
       'agent:intent:edit', '编辑意图', 1, 0, 'system', 'system'
WHERE NOT EXISTS (SELECT 1 FROM AUTH_AUTH_CODE WHERE CODE = 'agent:intent:edit');

INSERT INTO AUTH_TENANT_AUTH_CODE (TENANT_ID, AUTH_CODE_ID, STATUS, CREATE_TIME, UPDATE_TIME)
SELECT T.ID, C.ID, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
FROM AUTH_TENANT T
         CROSS JOIN AUTH_AUTH_CODE C
WHERE T.ID = 1
  AND T.STATUS = 1
  AND T.DEL_FLAG = 0
  AND C.CODE IN ('model:admin', 'agent:intent:edit')
  AND C.STATUS = 1
  AND C.DEL_FLAG = 0
  AND NOT EXISTS (
    SELECT 1
    FROM AUTH_TENANT_AUTH_CODE G
    WHERE G.TENANT_ID = T.ID
      AND G.AUTH_CODE_ID = C.ID
  );

INSERT INTO AUTH_ROLE_SCOPE_AUTH_CODE
    (ROLE_ID, AUTH_CODE_ID, TENANT_ID, STATUS, DEL_FLAG, CREATE_BY, UPDATE_BY)
SELECT R.ID, C.ID, T.ID, 1, 0, 'system', 'system'
FROM AUTH_ROLE R
         JOIN AUTH_TENANT T ON T.ID = R.TENANT_ID
         CROSS JOIN AUTH_AUTH_CODE C
WHERE T.ID = 1
  AND T.STATUS = 1
  AND T.DEL_FLAG = 0
  AND R.CODE IN ('super', 'admin')
  AND R.STATUS = 1
  AND R.DEL_FLAG = 0
  AND C.CODE IN ('model:admin', 'agent:intent:edit')
  AND C.STATUS = 1
  AND C.DEL_FLAG = 0
  AND NOT EXISTS (
    SELECT 1
    FROM AUTH_ROLE_SCOPE_AUTH_CODE G
    WHERE G.ROLE_ID = R.ID
      AND G.TENANT_ID = T.ID
      AND G.AUTH_CODE_ID = C.ID
  );
