-- 租户级业务模块开关。关闭仅更新 STATUS，不删除业务表或历史数据。
CREATE TABLE IF NOT EXISTS AUTH_TENANT_MODULE (
    TENANT_ID BIGINT NOT NULL,
    MODULE_ID VARCHAR(64) NOT NULL,
    STATUS TINYINT DEFAULT 1 NOT NULL,
    CREATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_AUTH_TENANT_MODULE PRIMARY KEY (TENANT_ID, MODULE_ID)
);

CREATE INDEX IF NOT EXISTS IDX_AUTH_TENANT_MODULE_STATUS
    ON AUTH_TENANT_MODULE (TENANT_ID, STATUS);

-- Education 是首个默认启用的业务模块；已有租户升级时保持原有可用性。
INSERT INTO AUTH_TENANT_MODULE (TENANT_ID, MODULE_ID, STATUS, CREATE_TIME, UPDATE_TIME)
SELECT T.ID, 'education', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
FROM AUTH_TENANT T
WHERE T.STATUS = 1
  AND T.DEL_FLAG = 0
  AND NOT EXISTS (
      SELECT 1
      FROM AUTH_TENANT_MODULE M
      WHERE M.TENANT_ID = T.ID
        AND M.MODULE_ID = 'education'
  );
