-- v4 权限增补；在事务内执行，不覆盖已有权限或授权的启停状态。
-- 启动升级由基线记录行锁串行化。外部数据库由部署方在维护窗口执行。
INSERT INTO AUTH_AUTH_CODE (ID, CODE, NAME, STATUS, DEL_FLAG, CREATE_BY, UPDATE_BY)
SELECT (SELECT COALESCE(MAX(ID), 0) + 1 FROM AUTH_AUTH_CODE),
       'platform:usage:read', '查看平台全租户用量', 1, 0, 'system', 'system'
WHERE NOT EXISTS (SELECT 1 FROM AUTH_AUTH_CODE WHERE CODE = 'platform:usage:read');

INSERT INTO AUTH_TENANT_AUTH_CODE (TENANT_ID, AUTH_CODE_ID, STATUS, CREATE_TIME, UPDATE_TIME)
SELECT T.ID, C.ID, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
FROM AUTH_TENANT T CROSS JOIN AUTH_AUTH_CODE C
WHERE T.ID = 1 AND T.STATUS = 1 AND T.DEL_FLAG = 0
  AND C.CODE = 'platform:usage:read' AND C.STATUS = 1 AND C.DEL_FLAG = 0
  AND NOT EXISTS (SELECT 1 FROM AUTH_TENANT_AUTH_CODE G
                  WHERE G.TENANT_ID = T.ID AND G.AUTH_CODE_ID = C.ID);

INSERT INTO AUTH_ROLE_SCOPE_AUTH_CODE
    (ROLE_ID, AUTH_CODE_ID, TENANT_ID, STATUS, DEL_FLAG, CREATE_BY, UPDATE_BY)
SELECT R.ID, C.ID, 1, 1, 0, 'system', 'system'
FROM AUTH_ROLE R JOIN AUTH_TENANT T ON T.ID = R.TENANT_ID
CROSS JOIN AUTH_AUTH_CODE C
WHERE T.ID = 1 AND T.STATUS = 1 AND T.DEL_FLAG = 0
  AND R.CODE = 'super' AND R.STATUS = 1 AND R.DEL_FLAG = 0
  AND C.CODE = 'platform:usage:read' AND C.STATUS = 1 AND C.DEL_FLAG = 0
  AND NOT EXISTS (SELECT 1 FROM AUTH_ROLE_SCOPE_AUTH_CODE G
                  WHERE G.ROLE_ID = R.ID AND G.TENANT_ID = T.ID AND G.AUTH_CODE_ID = C.ID);
