-- Initializer metadata. This table is not part of the 76 application tables.

CREATE TABLE "PUBLIC"."COMMON_SCHEMA_BASELINE" (
    "ID" INTEGER NOT NULL,
    "BASELINE_VERSION" CHARACTER VARYING(64) NOT NULL,
    "SEED_PROFILE" CHARACTER VARYING(64) NOT NULL,
    "INSTALLED_AT" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT "PK_COMMON_SCHEMA_BASELINE" PRIMARY KEY ("ID"),
    CONSTRAINT "CK_COMMON_SCHEMA_BASELINE_SINGLETON" CHECK ("ID" = 1)
);
