-- Persistent product assets are separate from the generic conversation source of truth.
CREATE CACHED TABLE IF NOT EXISTS "PUBLIC"."CHAT_CHARACTER_ASSET" (
    "ID" CHARACTER VARYING(64) NOT NULL,
    "TENANT_ID" BIGINT NOT NULL,
    "OWNER_USER_ID" BIGINT NOT NULL,
    "CARD_JSON" CHARACTER LARGE OBJECT NOT NULL,
    "VISIBILITY" CHARACTER VARYING(16) NOT NULL,
    "CREATED_AT" TIMESTAMP NOT NULL,
    "UPDATED_AT" TIMESTAMP NOT NULL,
    CONSTRAINT "PK_CHAT_CHARACTER_ASSET" PRIMARY KEY ("ID")
);
CREATE INDEX IF NOT EXISTS "IDX_CHAT_CHARACTER_OWNER" ON "PUBLIC"."CHAT_CHARACTER_ASSET"("TENANT_ID", "OWNER_USER_ID");
ALTER TABLE "PUBLIC"."CHAT_CHARACTER_ASSET" ADD COLUMN IF NOT EXISTS "PNG_DATA" BLOB;

CREATE CACHED TABLE IF NOT EXISTS "PUBLIC"."CHAT_PERSONA_ASSET" (
    "ID" CHARACTER VARYING(64) NOT NULL,
    "TENANT_ID" BIGINT NOT NULL,
    "OWNER_USER_ID" BIGINT NOT NULL,
    "PERSONA_JSON" CHARACTER LARGE OBJECT NOT NULL,
    "CREATED_AT" TIMESTAMP NOT NULL,
    "UPDATED_AT" TIMESTAMP NOT NULL,
    CONSTRAINT "PK_CHAT_PERSONA_ASSET" PRIMARY KEY ("ID")
);
CREATE INDEX IF NOT EXISTS "IDX_CHAT_PERSONA_OWNER" ON "PUBLIC"."CHAT_PERSONA_ASSET"("TENANT_ID", "OWNER_USER_ID");

CREATE CACHED TABLE IF NOT EXISTS "PUBLIC"."CHAT_LOREBOOK_ASSET" (
    "ID" CHARACTER VARYING(64) NOT NULL,
    "TENANT_ID" BIGINT NOT NULL,
    "OWNER_USER_ID" BIGINT NOT NULL,
    "ENTRY_JSON" CHARACTER LARGE OBJECT NOT NULL,
    "CREATED_AT" TIMESTAMP NOT NULL,
    "UPDATED_AT" TIMESTAMP NOT NULL,
    CONSTRAINT "PK_CHAT_LOREBOOK_ASSET" PRIMARY KEY ("ID")
);
CREATE INDEX IF NOT EXISTS "IDX_CHAT_LOREBOOK_OWNER" ON "PUBLIC"."CHAT_LOREBOOK_ASSET"("TENANT_ID", "OWNER_USER_ID");

CREATE CACHED TABLE IF NOT EXISTS "PUBLIC"."CHAT_PROMPT_TEMPLATE" (
    "ID" CHARACTER VARYING(64) NOT NULL,
    "TENANT_ID" BIGINT NOT NULL,
    "OWNER_USER_ID" BIGINT NOT NULL,
    "TEMPLATE_ID" CHARACTER VARYING(64) NOT NULL,
    "VERSION" INTEGER NOT NULL,
    "STATUS" CHARACTER VARYING(16) NOT NULL,
    "BODY" CHARACTER LARGE OBJECT NOT NULL,
    "VARIABLE_SCHEMA" CHARACTER LARGE OBJECT,
    "TEST_CASES" CHARACTER LARGE OBJECT,
    "CREATED_AT" TIMESTAMP NOT NULL,
    "PUBLISHED_AT" TIMESTAMP,
    CONSTRAINT "PK_CHAT_PROMPT_TEMPLATE" PRIMARY KEY ("ID"),
    CONSTRAINT "UK_CHAT_PROMPT_VERSION" UNIQUE ("TENANT_ID", "OWNER_USER_ID", "TEMPLATE_ID", "VERSION")
);
CREATE INDEX IF NOT EXISTS "IDX_CHAT_PROMPT_OWNER" ON "PUBLIC"."CHAT_PROMPT_TEMPLATE"("TENANT_ID", "OWNER_USER_ID", "TEMPLATE_ID");
