CREATE TABLE IF NOT EXISTS CHAT_GROUP_CHAT (
    ID VARCHAR(64) PRIMARY KEY,
    TENANT_ID BIGINT NOT NULL,
    OWNER_USER_ID BIGINT NOT NULL,
    NAME VARCHAR(255) NOT NULL,
    PARTICIPANTS_JSON CLOB NOT NULL,
    SPEAKER_POLICY VARCHAR(32) NOT NULL,
    MAX_TURNS INT NOT NULL,
    TOKEN_BUDGET INT NOT NULL,
    CREATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    UPDATED_AT TIMESTAMP WITH TIME ZONE NOT NULL
);
CREATE INDEX IF NOT EXISTS IDX_CHAT_GROUP_OWNER ON CHAT_GROUP_CHAT(TENANT_ID, OWNER_USER_ID);
